// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 微信登录请求
type WxLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                         // wx.login 获取的 code
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 设备唯一标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WxLoginRequest) Reset() {
	*x = WxLoginRequest{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WxLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxLoginRequest) ProtoMessage() {}

func (x *WxLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxLoginRequest.ProtoReflect.Descriptor instead.
func (*WxLoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *WxLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *WxLoginRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type WxLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	NeedBindPhone bool                   `protobuf:"varint,5,opt,name=need_bind_phone,json=needBindPhone,proto3" json:"need_bind_phone,omitempty"` // 是否需要绑定手机号
	Openid        string                 `protobuf:"bytes,6,opt,name=openid,proto3" json:"openid,omitempty"`                                       // 未绑定时返回，用于后续绑定
	HasCharacter  bool                   `protobuf:"varint,7,opt,name=has_character,json=hasCharacter,proto3" json:"has_character,omitempty"`      // 是否已创建角色
	PlayerInfo    *PlayerBrief           `protobuf:"bytes,8,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`             // 已有角色时返回
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WxLoginResponse) Reset() {
	*x = WxLoginResponse{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WxLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxLoginResponse) ProtoMessage() {}

func (x *WxLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxLoginResponse.ProtoReflect.Descriptor instead.
func (*WxLoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *WxLoginResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WxLoginResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *WxLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *WxLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *WxLoginResponse) GetNeedBindPhone() bool {
	if x != nil {
		return x.NeedBindPhone
	}
	return false
}

func (x *WxLoginResponse) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *WxLoginResponse) GetHasCharacter() bool {
	if x != nil {
		return x.HasCharacter
	}
	return false
}

func (x *WxLoginResponse) GetPlayerInfo() *PlayerBrief {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

// 抖音登录请求
type TtLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtLoginRequest) Reset() {
	*x = TtLoginRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtLoginRequest) ProtoMessage() {}

func (x *TtLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtLoginRequest.ProtoReflect.Descriptor instead.
func (*TtLoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *TtLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TtLoginRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type TtLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	NeedBindPhone bool                   `protobuf:"varint,5,opt,name=need_bind_phone,json=needBindPhone,proto3" json:"need_bind_phone,omitempty"`
	Openid        string                 `protobuf:"bytes,6,opt,name=openid,proto3" json:"openid,omitempty"`
	HasCharacter  bool                   `protobuf:"varint,7,opt,name=has_character,json=hasCharacter,proto3" json:"has_character,omitempty"`
	NeedConfirm   bool                   `protobuf:"varint,8,opt,name=need_confirm,json=needConfirm,proto3" json:"need_confirm,omitempty"` // 是否需要确认跨平台关联
	PlayerInfo    *PlayerBrief           `protobuf:"bytes,9,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtLoginResponse) Reset() {
	*x = TtLoginResponse{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtLoginResponse) ProtoMessage() {}

func (x *TtLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtLoginResponse.ProtoReflect.Descriptor instead.
func (*TtLoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *TtLoginResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TtLoginResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TtLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TtLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TtLoginResponse) GetNeedBindPhone() bool {
	if x != nil {
		return x.NeedBindPhone
	}
	return false
}

func (x *TtLoginResponse) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *TtLoginResponse) GetHasCharacter() bool {
	if x != nil {
		return x.HasCharacter
	}
	return false
}

func (x *TtLoginResponse) GetNeedConfirm() bool {
	if x != nil {
		return x.NeedConfirm
	}
	return false
}

func (x *TtLoginResponse) GetPlayerInfo() *PlayerBrief {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

// 手机号验证码登录
type PhoneLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"` // 短信验证码
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneLoginRequest) Reset() {
	*x = PhoneLoginRequest{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneLoginRequest) ProtoMessage() {}

func (x *PhoneLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneLoginRequest.ProtoReflect.Descriptor instead.
func (*PhoneLoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *PhoneLoginRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PhoneLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PhoneLoginRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type PhoneLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	HasCharacter  bool                   `protobuf:"varint,5,opt,name=has_character,json=hasCharacter,proto3" json:"has_character,omitempty"`
	PlayerInfo    *PlayerBrief           `protobuf:"bytes,6,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneLoginResponse) Reset() {
	*x = PhoneLoginResponse{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneLoginResponse) ProtoMessage() {}

func (x *PhoneLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneLoginResponse.ProtoReflect.Descriptor instead.
func (*PhoneLoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *PhoneLoginResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PhoneLoginResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PhoneLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PhoneLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *PhoneLoginResponse) GetHasCharacter() bool {
	if x != nil {
		return x.HasCharacter
	}
	return false
}

func (x *PhoneLoginResponse) GetPlayerInfo() *PlayerBrief {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

// 发送验证码
type SendCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Purpose       string                 `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"` // login / bind / reset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCodeRequest) Reset() {
	*x = SendCodeRequest{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeRequest) ProtoMessage() {}

func (x *SendCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeRequest.ProtoReflect.Descriptor instead.
func (*SendCodeRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *SendCodeRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendCodeRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type SendCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCodeResponse) Reset() {
	*x = SendCodeResponse{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeResponse) ProtoMessage() {}

func (x *SendCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeResponse.ProtoReflect.Descriptor instead.
func (*SendCodeResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *SendCodeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendCodeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SendCodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 绑定手机号
type BindPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Openid        string                 `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"` // wechat / douyin / app_ios / app_android
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"` // 短信验证码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindPhoneRequest) Reset() {
	*x = BindPhoneRequest{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindPhoneRequest) ProtoMessage() {}

func (x *BindPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindPhoneRequest.ProtoReflect.Descriptor instead.
func (*BindPhoneRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *BindPhoneRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *BindPhoneRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *BindPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *BindPhoneRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type BindPhoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	HasCharacter  bool                   `protobuf:"varint,5,opt,name=has_character,json=hasCharacter,proto3" json:"has_character,omitempty"`
	NeedConfirm   bool                   `protobuf:"varint,6,opt,name=need_confirm,json=needConfirm,proto3" json:"need_confirm,omitempty"` // 跨平台关联确认
	PlayerInfo    *PlayerBrief           `protobuf:"bytes,7,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindPhoneResponse) Reset() {
	*x = BindPhoneResponse{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindPhoneResponse) ProtoMessage() {}

func (x *BindPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindPhoneResponse.ProtoReflect.Descriptor instead.
func (*BindPhoneResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *BindPhoneResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BindPhoneResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BindPhoneResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *BindPhoneResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *BindPhoneResponse) GetHasCharacter() bool {
	if x != nil {
		return x.HasCharacter
	}
	return false
}

func (x *BindPhoneResponse) GetNeedConfirm() bool {
	if x != nil {
		return x.NeedConfirm
	}
	return false
}

func (x *BindPhoneResponse) GetPlayerInfo() *PlayerBrief {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

// 确认跨平台关联
type ConfirmBindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Openid        string                 `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBindRequest) Reset() {
	*x = ConfirmBindRequest{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBindRequest) ProtoMessage() {}

func (x *ConfirmBindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBindRequest.ProtoReflect.Descriptor instead.
func (*ConfirmBindRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ConfirmBindRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *ConfirmBindRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ConfirmBindRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ConfirmBindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	HasCharacter  bool                   `protobuf:"varint,5,opt,name=has_character,json=hasCharacter,proto3" json:"has_character,omitempty"`
	PlayerInfo    *PlayerBrief           `protobuf:"bytes,6,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBindResponse) Reset() {
	*x = ConfirmBindResponse{}
	mi := &file_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBindResponse) ProtoMessage() {}

func (x *ConfirmBindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBindResponse.ProtoReflect.Descriptor instead.
func (*ConfirmBindResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ConfirmBindResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfirmBindResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ConfirmBindResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConfirmBindResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *ConfirmBindResponse) GetHasCharacter() bool {
	if x != nil {
		return x.HasCharacter
	}
	return false
}

func (x *ConfirmBindResponse) GetPlayerInfo() *PlayerBrief {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

// Token 刷新
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{12}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{13}
}

func (x *RefreshTokenResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RefreshTokenResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RefreshTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// Token 校验
type CheckTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTokenRequest) Reset() {
	*x = CheckTokenRequest{}
	mi := &file_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenRequest) ProtoMessage() {}

func (x *CheckTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenRequest.ProtoReflect.Descriptor instead.
func (*CheckTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{14}
}

func (x *CheckTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CheckTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	AccountId     int64                  `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	HasCharacter  bool                   `protobuf:"varint,4,opt,name=has_character,json=hasCharacter,proto3" json:"has_character,omitempty"`
	PlayerInfo    *PlayerBrief           `protobuf:"bytes,5,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTokenResponse) Reset() {
	*x = CheckTokenResponse{}
	mi := &file_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenResponse) ProtoMessage() {}

func (x *CheckTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenResponse.ProtoReflect.Descriptor instead.
func (*CheckTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{15}
}

func (x *CheckTokenResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CheckTokenResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CheckTokenResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CheckTokenResponse) GetHasCharacter() bool {
	if x != nil {
		return x.HasCharacter
	}
	return false
}

func (x *CheckTokenResponse) GetPlayerInfo() *PlayerBrief {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

// 角色简要信息
type PlayerBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gender        int32                  `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	LevelStage    int32                  `protobuf:"varint,4,opt,name=level_stage,json=levelStage,proto3" json:"level_stage,omitempty"`
	LevelTier     int32                  `protobuf:"varint,5,opt,name=level_tier,json=levelTier,proto3" json:"level_tier,omitempty"`
	LevelStep     int32                  `protobuf:"varint,6,opt,name=level_step,json=levelStep,proto3" json:"level_step,omitempty"`
	SceneId       int32                  `protobuf:"varint,7,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	PosX          float32                `protobuf:"fixed32,8,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          float32                `protobuf:"fixed32,9,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBrief) Reset() {
	*x = PlayerBrief{}
	mi := &file_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBrief) ProtoMessage() {}

func (x *PlayerBrief) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBrief.ProtoReflect.Descriptor instead.
func (*PlayerBrief) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{16}
}

func (x *PlayerBrief) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerBrief) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerBrief) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *PlayerBrief) GetLevelStage() int32 {
	if x != nil {
		return x.LevelStage
	}
	return 0
}

func (x *PlayerBrief) GetLevelTier() int32 {
	if x != nil {
		return x.LevelTier
	}
	return 0
}

func (x *PlayerBrief) GetLevelStep() int32 {
	if x != nil {
		return x.LevelStep
	}
	return 0
}

func (x *PlayerBrief) GetSceneId() int32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *PlayerBrief) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *PlayerBrief) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\fxunxian.auth\"A\n" +
	"\x0eWxLoginRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"\x93\x02\n" +
	"\x0fWxLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12&\n" +
	"\x0fneed_bind_phone\x18\x05 \x01(\bR\rneedBindPhone\x12\x16\n" +
	"\x06openid\x18\x06 \x01(\tR\x06openid\x12#\n" +
	"\rhas_character\x18\a \x01(\bR\fhasCharacter\x12:\n" +
	"\vplayer_info\x18\b \x01(\v2\x19.xunxian.auth.PlayerBriefR\n" +
	"playerInfo\"A\n" +
	"\x0eTtLoginRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"\xb6\x02\n" +
	"\x0fTtLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12&\n" +
	"\x0fneed_bind_phone\x18\x05 \x01(\bR\rneedBindPhone\x12\x16\n" +
	"\x06openid\x18\x06 \x01(\tR\x06openid\x12#\n" +
	"\rhas_character\x18\a \x01(\bR\fhasCharacter\x12!\n" +
	"\fneed_confirm\x18\b \x01(\bR\vneedConfirm\x12:\n" +
	"\vplayer_info\x18\t \x01(\v2\x19.xunxian.auth.PlayerBriefR\n" +
	"playerInfo\"Z\n" +
	"\x11PhoneLoginRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\"\xd6\x01\n" +
	"\x12PhoneLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12#\n" +
	"\rhas_character\x18\x05 \x01(\bR\fhasCharacter\x12:\n" +
	"\vplayer_info\x18\x06 \x01(\v2\x19.xunxian.auth.PlayerBriefR\n" +
	"playerInfo\"A\n" +
	"\x0fSendCodeRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\"R\n" +
	"\x10SendCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"p\n" +
	"\x10BindPhoneRequest\x12\x16\n" +
	"\x06openid\x18\x01 \x01(\tR\x06openid\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\"\xf8\x01\n" +
	"\x11BindPhoneResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12#\n" +
	"\rhas_character\x18\x05 \x01(\bR\fhasCharacter\x12!\n" +
	"\fneed_confirm\x18\x06 \x01(\bR\vneedConfirm\x12:\n" +
	"\vplayer_info\x18\a \x01(\v2\x19.xunxian.auth.PlayerBriefR\n" +
	"playerInfo\"^\n" +
	"\x12ConfirmBindRequest\x12\x16\n" +
	"\x06openid\x18\x01 \x01(\tR\x06openid\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"\xd7\x01\n" +
	"\x13ConfirmBindResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12#\n" +
	"\rhas_character\x18\x05 \x01(\bR\fhasCharacter\x12:\n" +
	"\vplayer_info\x18\x06 \x01(\v2\x19.xunxian.auth.PlayerBriefR\n" +
	"playerInfo\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"w\n" +
	"\x14RefreshTokenResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\")\n" +
	"\x11CheckTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xba\x01\n" +
	"\x12CheckTokenResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\x03R\taccountId\x12#\n" +
	"\rhas_character\x18\x04 \x01(\bR\fhasCharacter\x12:\n" +
	"\vplayer_info\x18\x05 \x01(\v2\x19.xunxian.auth.PlayerBriefR\n" +
	"playerInfo\"\xfa\x01\n" +
	"\vPlayerBrief\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\x05R\x06gender\x12\x1f\n" +
	"\vlevel_stage\x18\x04 \x01(\x05R\n" +
	"levelStage\x12\x1d\n" +
	"\n" +
	"level_tier\x18\x05 \x01(\x05R\tlevelTier\x12\x1d\n" +
	"\n" +
	"level_step\x18\x06 \x01(\x05R\tlevelStep\x12\x19\n" +
	"\bscene_id\x18\a \x01(\x05R\asceneId\x12\x13\n" +
	"\x05pos_x\x18\b \x01(\x02R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\t \x01(\x02R\x04posYB\x14Z\x12xunxian/proto/authb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_auth_proto_goTypes = []any{
	(*WxLoginRequest)(nil),       // 0: xunxian.auth.WxLoginRequest
	(*WxLoginResponse)(nil),      // 1: xunxian.auth.WxLoginResponse
	(*TtLoginRequest)(nil),       // 2: xunxian.auth.TtLoginRequest
	(*TtLoginResponse)(nil),      // 3: xunxian.auth.TtLoginResponse
	(*PhoneLoginRequest)(nil),    // 4: xunxian.auth.PhoneLoginRequest
	(*PhoneLoginResponse)(nil),   // 5: xunxian.auth.PhoneLoginResponse
	(*SendCodeRequest)(nil),      // 6: xunxian.auth.SendCodeRequest
	(*SendCodeResponse)(nil),     // 7: xunxian.auth.SendCodeResponse
	(*BindPhoneRequest)(nil),     // 8: xunxian.auth.BindPhoneRequest
	(*BindPhoneResponse)(nil),    // 9: xunxian.auth.BindPhoneResponse
	(*ConfirmBindRequest)(nil),   // 10: xunxian.auth.ConfirmBindRequest
	(*ConfirmBindResponse)(nil),  // 11: xunxian.auth.ConfirmBindResponse
	(*RefreshTokenRequest)(nil),  // 12: xunxian.auth.RefreshTokenRequest
	(*RefreshTokenResponse)(nil), // 13: xunxian.auth.RefreshTokenResponse
	(*CheckTokenRequest)(nil),    // 14: xunxian.auth.CheckTokenRequest
	(*CheckTokenResponse)(nil),   // 15: xunxian.auth.CheckTokenResponse
	(*PlayerBrief)(nil),          // 16: xunxian.auth.PlayerBrief
}
var file_auth_proto_depIdxs = []int32{
	16, // 0: xunxian.auth.WxLoginResponse.player_info:type_name -> xunxian.auth.PlayerBrief
	16, // 1: xunxian.auth.TtLoginResponse.player_info:type_name -> xunxian.auth.PlayerBrief
	16, // 2: xunxian.auth.PhoneLoginResponse.player_info:type_name -> xunxian.auth.PlayerBrief
	16, // 3: xunxian.auth.BindPhoneResponse.player_info:type_name -> xunxian.auth.PlayerBrief
	16, // 4: xunxian.auth.ConfirmBindResponse.player_info:type_name -> xunxian.auth.PlayerBrief
	16, // 5: xunxian.auth.CheckTokenResponse.player_info:type_name -> xunxian.auth.PlayerBrief
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
