// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: scene.proto

package scene

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 进入场景
type EnterSceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SceneId       int32                  `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterSceneRequest) Reset() {
	*x = EnterSceneRequest{}
	mi := &file_scene_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSceneRequest) ProtoMessage() {}

func (x *EnterSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSceneRequest.ProtoReflect.Descriptor instead.
func (*EnterSceneRequest) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{0}
}

func (x *EnterSceneRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *EnterSceneRequest) GetSceneId() int32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

type EnterSceneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Entities      []*EntityState         `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"` // 可见实体列表
	PosX          float32                `protobuf:"fixed32,4,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          float32                `protobuf:"fixed32,5,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterSceneResponse) Reset() {
	*x = EnterSceneResponse{}
	mi := &file_scene_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterSceneResponse) ProtoMessage() {}

func (x *EnterSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterSceneResponse.ProtoReflect.Descriptor instead.
func (*EnterSceneResponse) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{1}
}

func (x *EnterSceneResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EnterSceneResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *EnterSceneResponse) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *EnterSceneResponse) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *EnterSceneResponse) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

// 离开场景
type LeaveSceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SceneId       int32                  `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveSceneRequest) Reset() {
	*x = LeaveSceneRequest{}
	mi := &file_scene_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSceneRequest) ProtoMessage() {}

func (x *LeaveSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSceneRequest.ProtoReflect.Descriptor instead.
func (*LeaveSceneRequest) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveSceneRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *LeaveSceneRequest) GetSceneId() int32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

type LeaveSceneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveSceneResponse) Reset() {
	*x = LeaveSceneResponse{}
	mi := &file_scene_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSceneResponse) ProtoMessage() {}

func (x *LeaveSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSceneResponse.ProtoReflect.Descriptor instead.
func (*LeaveSceneResponse) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveSceneResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LeaveSceneResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 移动请求（客户端 → 服务端）
type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`    // 目标x坐标
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`    // 目标y坐标
	Seq           uint32                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"` // 帧序号
	Dir           int32                  `protobuf:"varint,4,opt,name=dir,proto3" json:"dir,omitempty"` // 朝向 0-7
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_scene_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{4}
}

func (x *MoveRequest) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveRequest) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MoveRequest) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MoveRequest) GetDir() int32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

// 服务端同步帧（服务端 → 客户端）
type SyncFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*EntityState         `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	ServerSeq     uint32                 `protobuf:"varint,2,opt,name=server_seq,json=serverSeq,proto3" json:"server_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFrame) Reset() {
	*x = SyncFrame{}
	mi := &file_scene_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFrame) ProtoMessage() {}

func (x *SyncFrame) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFrame.ProtoReflect.Descriptor instead.
func (*SyncFrame) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{5}
}

func (x *SyncFrame) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SyncFrame) GetServerSeq() uint32 {
	if x != nil {
		return x.ServerSeq
	}
	return 0
}

// 实体状态
type EntityState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      int64                  `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Dir           int32                  `protobuf:"varint,4,opt,name=dir,proto3" json:"dir,omitempty"`       // 朝向 0-7
	Action        int32                  `protobuf:"varint,5,opt,name=action,proto3" json:"action,omitempty"` // 0=idle 1=walk 2=run 3=attack 4=sit
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	EntityType    int32                  `protobuf:"varint,7,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // 1=player 2=npc
	Gender        int32                  `protobuf:"varint,8,opt,name=gender,proto3" json:"gender,omitempty"`
	LevelStage    int32                  `protobuf:"varint,9,opt,name=level_stage,json=levelStage,proto3" json:"level_stage,omitempty"`
	LevelTier     int32                  `protobuf:"varint,10,opt,name=level_tier,json=levelTier,proto3" json:"level_tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityState) Reset() {
	*x = EntityState{}
	mi := &file_scene_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityState) ProtoMessage() {}

func (x *EntityState) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityState.ProtoReflect.Descriptor instead.
func (*EntityState) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{6}
}

func (x *EntityState) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *EntityState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *EntityState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *EntityState) GetDir() int32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

func (x *EntityState) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *EntityState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityState) GetEntityType() int32 {
	if x != nil {
		return x.EntityType
	}
	return 0
}

func (x *EntityState) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *EntityState) GetLevelStage() int32 {
	if x != nil {
		return x.LevelStage
	}
	return 0
}

func (x *EntityState) GetLevelTier() int32 {
	if x != nil {
		return x.LevelTier
	}
	return 0
}

// 实体进入可视范围事件
type EnterEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *EntityState           `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterEvent) Reset() {
	*x = EnterEvent{}
	mi := &file_scene_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterEvent) ProtoMessage() {}

func (x *EnterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterEvent.ProtoReflect.Descriptor instead.
func (*EnterEvent) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{7}
}

func (x *EnterEvent) GetEntity() *EntityState {
	if x != nil {
		return x.Entity
	}
	return nil
}

// 实体离开可视范围事件
type LeaveEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      int64                  `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveEvent) Reset() {
	*x = LeaveEvent{}
	mi := &file_scene_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveEvent) ProtoMessage() {}

func (x *LeaveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveEvent.ProtoReflect.Descriptor instead.
func (*LeaveEvent) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveEvent) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

// NPC 交互
type InteractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	NpcId         int32                  `protobuf:"varint,2,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // shop / quest / talk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractRequest) Reset() {
	*x = InteractRequest{}
	mi := &file_scene_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractRequest) ProtoMessage() {}

func (x *InteractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractRequest.ProtoReflect.Descriptor instead.
func (*InteractRequest) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{9}
}

func (x *InteractRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *InteractRequest) GetNpcId() int32 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *InteractRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type InteractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // dialog / shop / quest
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // JSON 格式的交互数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractResponse) Reset() {
	*x = InteractResponse{}
	mi := &file_scene_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractResponse) ProtoMessage() {}

func (x *InteractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractResponse.ProtoReflect.Descriptor instead.
func (*InteractResponse) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{10}
}

func (x *InteractResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InteractResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *InteractResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InteractResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// 聊天消息
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderName    string                 `protobuf:"bytes,2,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Channel       int32                  `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"` // 1=世界 2=帮派 3=私聊
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_scene_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{11}
}

func (x *ChatMessage) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatMessage) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ChatMessage) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 发送聊天
type SendChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       int32                  `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 私聊时指定目标
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatRequest) Reset() {
	*x = SendChatRequest{}
	mi := &file_scene_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatRequest) ProtoMessage() {}

func (x *SendChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatRequest.ProtoReflect.Descriptor instead.
func (*SendChatRequest) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{12}
}

func (x *SendChatRequest) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *SendChatRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendChatRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type SendChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatResponse) Reset() {
	*x = SendChatResponse{}
	mi := &file_scene_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatResponse) ProtoMessage() {}

func (x *SendChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatResponse.ProtoReflect.Descriptor instead.
func (*SendChatResponse) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{13}
}

func (x *SendChatResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendChatResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 心跳
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_scene_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{14}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_scene_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{15}
}

func (x *HeartbeatAck) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// 踢下线事件
type KickOutEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickOutEvent) Reset() {
	*x = KickOutEvent{}
	mi := &file_scene_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickOutEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickOutEvent) ProtoMessage() {}

func (x *KickOutEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickOutEvent.ProtoReflect.Descriptor instead.
func (*KickOutEvent) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{16}
}

func (x *KickOutEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 重连请求
type ReconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	LastSeq       uint32                 `protobuf:"varint,3,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"` // 客户端最后收到的帧序号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectRequest) Reset() {
	*x = ReconnectRequest{}
	mi := &file_scene_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectRequest) ProtoMessage() {}

func (x *ReconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectRequest.ProtoReflect.Descriptor instead.
func (*ReconnectRequest) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{17}
}

func (x *ReconnectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ReconnectRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ReconnectRequest) GetLastSeq() uint32 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

type ReconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Entities      []*EntityState         `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"`
	PosX          float32                `protobuf:"fixed32,4,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          float32                `protobuf:"fixed32,5,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	ServerSeq     uint32                 `protobuf:"varint,6,opt,name=server_seq,json=serverSeq,proto3" json:"server_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectResponse) Reset() {
	*x = ReconnectResponse{}
	mi := &file_scene_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectResponse) ProtoMessage() {}

func (x *ReconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectResponse.ProtoReflect.Descriptor instead.
func (*ReconnectResponse) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{18}
}

func (x *ReconnectResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReconnectResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ReconnectResponse) GetEntities() []*EntityState {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ReconnectResponse) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *ReconnectResponse) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *ReconnectResponse) GetServerSeq() uint32 {
	if x != nil {
		return x.ServerSeq
	}
	return 0
}

// WebSocket 消息信封
type WsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // 消息类型
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // Protobuf 序列化的消息体
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsMessage) Reset() {
	*x = WsMessage{}
	mi := &file_scene_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsMessage) ProtoMessage() {}

func (x *WsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_scene_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsMessage.ProtoReflect.Descriptor instead.
func (*WsMessage) Descriptor() ([]byte, []int) {
	return file_scene_proto_rawDescGZIP(), []int{19}
}

func (x *WsMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WsMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_scene_proto protoreflect.FileDescriptor

const file_scene_proto_rawDesc = "" +
	"\n" +
	"\vscene.proto\x12\rxunxian.scene\"K\n" +
	"\x11EnterSceneRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x19\n" +
	"\bscene_id\x18\x02 \x01(\x05R\asceneId\"\x9c\x01\n" +
	"\x12EnterSceneResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x126\n" +
	"\bentities\x18\x03 \x03(\v2\x1a.xunxian.scene.EntityStateR\bentities\x12\x13\n" +
	"\x05pos_x\x18\x04 \x01(\x02R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x05 \x01(\x02R\x04posY\"K\n" +
	"\x11LeaveSceneRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x19\n" +
	"\bscene_id\x18\x02 \x01(\x05R\asceneId\":\n" +
	"\x12LeaveSceneResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"M\n" +
	"\vMoveRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\rR\x03seq\x12\x10\n" +
	"\x03dir\x18\x04 \x01(\x05R\x03dir\"b\n" +
	"\tSyncFrame\x126\n" +
	"\bentities\x18\x01 \x03(\v2\x1a.xunxian.scene.EntityStateR\bentities\x12\x1d\n" +
	"\n" +
	"server_seq\x18\x02 \x01(\rR\tserverSeq\"\xfd\x01\n" +
	"\vEntityState\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x03R\bentityId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x10\n" +
	"\x03dir\x18\x04 \x01(\x05R\x03dir\x12\x16\n" +
	"\x06action\x18\x05 \x01(\x05R\x06action\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x1f\n" +
	"\ventity_type\x18\a \x01(\x05R\n" +
	"entityType\x12\x16\n" +
	"\x06gender\x18\b \x01(\x05R\x06gender\x12\x1f\n" +
	"\vlevel_stage\x18\t \x01(\x05R\n" +
	"levelStage\x12\x1d\n" +
	"\n" +
	"level_tier\x18\n" +
	" \x01(\x05R\tlevelTier\"@\n" +
	"\n" +
	"EnterEvent\x122\n" +
	"\x06entity\x18\x01 \x01(\v2\x1a.xunxian.scene.EntityStateR\x06entity\")\n" +
	"\n" +
	"LeaveEvent\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x03R\bentityId\"]\n" +
	"\x0fInteractRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x15\n" +
	"\x06npc_id\x18\x02 \x01(\x05R\x05npcId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"`\n" +
	"\x10InteractResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\"\x97\x01\n" +
	"\vChatMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x02 \x01(\tR\n" +
	"senderName\x12\x18\n" +
	"\achannel\x18\x03 \x01(\x05R\achannel\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\\\n" +
	"\x0fSendChatRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\x05R\achannel\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\"8\n" +
	"\x10SendChatResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"/\n" +
	"\fHeartbeatAck\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\"&\n" +
	"\fKickOutEvent\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"`\n" +
	"\x10ReconnectRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x19\n" +
	"\blast_seq\x18\x03 \x01(\rR\alastSeq\"\xba\x01\n" +
	"\x11ReconnectResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x126\n" +
	"\bentities\x18\x03 \x03(\v2\x1a.xunxian.scene.EntityStateR\bentities\x12\x13\n" +
	"\x05pos_x\x18\x04 \x01(\x02R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x05 \x01(\x02R\x04posY\x12\x1d\n" +
	"\n" +
	"server_seq\x18\x06 \x01(\rR\tserverSeq\"9\n" +
	"\tWsMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayloadB\x15Z\x13xunxian/proto/sceneb\x06proto3"

var (
	file_scene_proto_rawDescOnce sync.Once
	file_scene_proto_rawDescData []byte
)

func file_scene_proto_rawDescGZIP() []byte {
	file_scene_proto_rawDescOnce.Do(func() {
		file_scene_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scene_proto_rawDesc), len(file_scene_proto_rawDesc)))
	})
	return file_scene_proto_rawDescData
}

var file_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_scene_proto_goTypes = []any{
	(*EnterSceneRequest)(nil),  // 0: xunxian.scene.EnterSceneRequest
	(*EnterSceneResponse)(nil), // 1: xunxian.scene.EnterSceneResponse
	(*LeaveSceneRequest)(nil),  // 2: xunxian.scene.LeaveSceneRequest
	(*LeaveSceneResponse)(nil), // 3: xunxian.scene.LeaveSceneResponse
	(*MoveRequest)(nil),        // 4: xunxian.scene.MoveRequest
	(*SyncFrame)(nil),          // 5: xunxian.scene.SyncFrame
	(*EntityState)(nil),        // 6: xunxian.scene.EntityState
	(*EnterEvent)(nil),         // 7: xunxian.scene.EnterEvent
	(*LeaveEvent)(nil),         // 8: xunxian.scene.LeaveEvent
	(*InteractRequest)(nil),    // 9: xunxian.scene.InteractRequest
	(*InteractResponse)(nil),   // 10: xunxian.scene.InteractResponse
	(*ChatMessage)(nil),        // 11: xunxian.scene.ChatMessage
	(*SendChatRequest)(nil),    // 12: xunxian.scene.SendChatRequest
	(*SendChatResponse)(nil),   // 13: xunxian.scene.SendChatResponse
	(*Heartbeat)(nil),          // 14: xunxian.scene.Heartbeat
	(*HeartbeatAck)(nil),       // 15: xunxian.scene.HeartbeatAck
	(*KickOutEvent)(nil),       // 16: xunxian.scene.KickOutEvent
	(*ReconnectRequest)(nil),   // 17: xunxian.scene.ReconnectRequest
	(*ReconnectResponse)(nil),  // 18: xunxian.scene.ReconnectResponse
	(*WsMessage)(nil),          // 19: xunxian.scene.WsMessage
}
var file_scene_proto_depIdxs = []int32{
	6, // 0: xunxian.scene.EnterSceneResponse.entities:type_name -> xunxian.scene.EntityState
	6, // 1: xunxian.scene.SyncFrame.entities:type_name -> xunxian.scene.EntityState
	6, // 2: xunxian.scene.EnterEvent.entity:type_name -> xunxian.scene.EntityState
	6, // 3: xunxian.scene.ReconnectResponse.entities:type_name -> xunxian.scene.EntityState
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_scene_proto_init() }
func file_scene_proto_init() {
	if File_scene_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scene_proto_rawDesc), len(file_scene_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scene_proto_goTypes,
		DependencyIndexes: file_scene_proto_depIdxs,
		MessageInfos:      file_scene_proto_msgTypes,
	}.Build()
	File_scene_proto = out.File
	file_scene_proto_goTypes = nil
	file_scene_proto_depIdxs = nil
}
