// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: death.proto

package death

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 触发死亡
type DeathTriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	DeathType     int32                  `protobuf:"varint,2,opt,name=death_type,json=deathType,proto3" json:"death_type,omitempty"` // 1=自由探索死 2=魂飞魄散 3=夺舍失败
	IsDungeon     bool                   `protobuf:"varint,3,opt,name=is_dungeon,json=isDungeon,proto3" json:"is_dungeon,omitempty"` // true=副本内死亡（不触发死亡机制）
	LocationX     int32                  `protobuf:"varint,4,opt,name=location_x,json=locationX,proto3" json:"location_x,omitempty"`
	LocationY     int32                  `protobuf:"varint,5,opt,name=location_y,json=locationY,proto3" json:"location_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeathTriggerRequest) Reset() {
	*x = DeathTriggerRequest{}
	mi := &file_death_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeathTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeathTriggerRequest) ProtoMessage() {}

func (x *DeathTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeathTriggerRequest.ProtoReflect.Descriptor instead.
func (*DeathTriggerRequest) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{0}
}

func (x *DeathTriggerRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *DeathTriggerRequest) GetDeathType() int32 {
	if x != nil {
		return x.DeathType
	}
	return 0
}

func (x *DeathTriggerRequest) GetIsDungeon() bool {
	if x != nil {
		return x.IsDungeon
	}
	return false
}

func (x *DeathTriggerRequest) GetLocationX() int32 {
	if x != nil {
		return x.LocationX
	}
	return 0
}

func (x *DeathTriggerRequest) GetLocationY() int32 {
	if x != nil {
		return x.LocationY
	}
	return 0
}

type DeathTriggerResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg            string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	IsDungeonDeath bool                   `protobuf:"varint,3,opt,name=is_dungeon_death,json=isDungeonDeath,proto3" json:"is_dungeon_death,omitempty"`
	Options        []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"` // reincarnation / ghost_cultivation
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeathTriggerResponse) Reset() {
	*x = DeathTriggerResponse{}
	mi := &file_death_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeathTriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeathTriggerResponse) ProtoMessage() {}

func (x *DeathTriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeathTriggerResponse.ProtoReflect.Descriptor instead.
func (*DeathTriggerResponse) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{1}
}

func (x *DeathTriggerResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeathTriggerResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DeathTriggerResponse) GetIsDungeonDeath() bool {
	if x != nil {
		return x.IsDungeonDeath
	}
	return false
}

func (x *DeathTriggerResponse) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// 六道轮回
type ReincarnationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ForceBeast    bool                   `protobuf:"varint,2,opt,name=force_beast,json=forceBeast,proto3" json:"force_beast,omitempty"` // true=三次夺舍强制变兽
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReincarnationRequest) Reset() {
	*x = ReincarnationRequest{}
	mi := &file_death_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReincarnationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReincarnationRequest) ProtoMessage() {}

func (x *ReincarnationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReincarnationRequest.ProtoReflect.Descriptor instead.
func (*ReincarnationRequest) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{2}
}

func (x *ReincarnationRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *ReincarnationRequest) GetForceBeast() bool {
	if x != nil {
		return x.ForceBeast
	}
	return false
}

type ReincarnationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Code              int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg               string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ReincarnationType int32                  `protobuf:"varint,3,opt,name=reincarnation_type,json=reincarnationType,proto3" json:"reincarnation_type,omitempty"` // 1=天道...6=地狱道
	ReincarnationName string                 `protobuf:"bytes,4,opt,name=reincarnation_name,json=reincarnationName,proto3" json:"reincarnation_name,omitempty"`
	NewAttrs          *BaseAttrs             `protobuf:"bytes,5,opt,name=new_attrs,json=newAttrs,proto3" json:"new_attrs,omitempty"`
	IsBeast           bool                   `protobuf:"varint,6,opt,name=is_beast,json=isBeast,proto3" json:"is_beast,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReincarnationResponse) Reset() {
	*x = ReincarnationResponse{}
	mi := &file_death_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReincarnationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReincarnationResponse) ProtoMessage() {}

func (x *ReincarnationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReincarnationResponse.ProtoReflect.Descriptor instead.
func (*ReincarnationResponse) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{3}
}

func (x *ReincarnationResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReincarnationResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ReincarnationResponse) GetReincarnationType() int32 {
	if x != nil {
		return x.ReincarnationType
	}
	return 0
}

func (x *ReincarnationResponse) GetReincarnationName() string {
	if x != nil {
		return x.ReincarnationName
	}
	return ""
}

func (x *ReincarnationResponse) GetNewAttrs() *BaseAttrs {
	if x != nil {
		return x.NewAttrs
	}
	return nil
}

func (x *ReincarnationResponse) GetIsBeast() bool {
	if x != nil {
		return x.IsBeast
	}
	return false
}

// 进入鬼修
type GhostEnterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GhostEnterRequest) Reset() {
	*x = GhostEnterRequest{}
	mi := &file_death_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GhostEnterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GhostEnterRequest) ProtoMessage() {}

func (x *GhostEnterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GhostEnterRequest.ProtoReflect.Descriptor instead.
func (*GhostEnterRequest) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{4}
}

func (x *GhostEnterRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type GhostEnterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	GhostMode     int32                  `protobuf:"varint,3,opt,name=ghost_mode,json=ghostMode,proto3" json:"ghost_mode,omitempty"`
	SoulHpMax     int32                  `protobuf:"varint,4,opt,name=soul_hp_max,json=soulHpMax,proto3" json:"soul_hp_max,omitempty"`
	SoulHpCurrent int32                  `protobuf:"varint,5,opt,name=soul_hp_current,json=soulHpCurrent,proto3" json:"soul_hp_current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GhostEnterResponse) Reset() {
	*x = GhostEnterResponse{}
	mi := &file_death_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GhostEnterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GhostEnterResponse) ProtoMessage() {}

func (x *GhostEnterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GhostEnterResponse.ProtoReflect.Descriptor instead.
func (*GhostEnterResponse) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{5}
}

func (x *GhostEnterResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GhostEnterResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GhostEnterResponse) GetGhostMode() int32 {
	if x != nil {
		return x.GhostMode
	}
	return 0
}

func (x *GhostEnterResponse) GetSoulHpMax() int32 {
	if x != nil {
		return x.SoulHpMax
	}
	return 0
}

func (x *GhostEnterResponse) GetSoulHpCurrent() int32 {
	if x != nil {
		return x.SoulHpCurrent
	}
	return 0
}

// 鬼修重聚肉身
type GhostExitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GhostExitRequest) Reset() {
	*x = GhostExitRequest{}
	mi := &file_death_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GhostExitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GhostExitRequest) ProtoMessage() {}

func (x *GhostExitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GhostExitRequest.ProtoReflect.Descriptor instead.
func (*GhostExitRequest) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{6}
}

func (x *GhostExitRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type GhostExitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GhostExitResponse) Reset() {
	*x = GhostExitResponse{}
	mi := &file_death_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GhostExitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GhostExitResponse) ProtoMessage() {}

func (x *GhostExitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GhostExitResponse.ProtoReflect.Descriptor instead.
func (*GhostExitResponse) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{7}
}

func (x *GhostExitResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GhostExitResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 发起夺舍
type PossessStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	TargetType    int32                  `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // 1=NPC 2=玩家
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetName    string                 `protobuf:"bytes,4,opt,name=target_name,json=targetName,proto3" json:"target_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PossessStartRequest) Reset() {
	*x = PossessStartRequest{}
	mi := &file_death_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PossessStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PossessStartRequest) ProtoMessage() {}

func (x *PossessStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PossessStartRequest.ProtoReflect.Descriptor instead.
func (*PossessStartRequest) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{8}
}

func (x *PossessStartRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *PossessStartRequest) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *PossessStartRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *PossessStartRequest) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

type PossessStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	SuccessRate   float64                `protobuf:"fixed64,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	PossessorShen int32                  `protobuf:"varint,5,opt,name=possessor_shen,json=possessorShen,proto3" json:"possessor_shen,omitempty"`
	TargetShen    int32                  `protobuf:"varint,6,opt,name=target_shen,json=targetShen,proto3" json:"target_shen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PossessStartResponse) Reset() {
	*x = PossessStartResponse{}
	mi := &file_death_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PossessStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PossessStartResponse) ProtoMessage() {}

func (x *PossessStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PossessStartResponse.ProtoReflect.Descriptor instead.
func (*PossessStartResponse) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{9}
}

func (x *PossessStartResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PossessStartResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PossessStartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PossessStartResponse) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *PossessStartResponse) GetPossessorShen() int32 {
	if x != nil {
		return x.PossessorShen
	}
	return 0
}

func (x *PossessStartResponse) GetTargetShen() int32 {
	if x != nil {
		return x.TargetShen
	}
	return 0
}

// 夺舍结算
type PossessResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PossessResultRequest) Reset() {
	*x = PossessResultRequest{}
	mi := &file_death_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PossessResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PossessResultRequest) ProtoMessage() {}

func (x *PossessResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PossessResultRequest.ProtoReflect.Descriptor instead.
func (*PossessResultRequest) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{10}
}

func (x *PossessResultRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *PossessResultRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PossessResultRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type PossessResultResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg             string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	IsPublicEnemy   bool                   `protobuf:"varint,3,opt,name=is_public_enemy,json=isPublicEnemy,proto3" json:"is_public_enemy,omitempty"`
	ForceBeast      bool                   `protobuf:"varint,4,opt,name=force_beast,json=forceBeast,proto3" json:"force_beast,omitempty"`
	PossessCount    int32                  `protobuf:"varint,5,opt,name=possess_count,json=possessCount,proto3" json:"possess_count,omitempty"`
	PlunderedShen   int32                  `protobuf:"varint,6,opt,name=plundered_shen,json=plunderedShen,proto3" json:"plundered_shen,omitempty"`
	MustReincarnate bool                   `protobuf:"varint,7,opt,name=must_reincarnate,json=mustReincarnate,proto3" json:"must_reincarnate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PossessResultResponse) Reset() {
	*x = PossessResultResponse{}
	mi := &file_death_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PossessResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PossessResultResponse) ProtoMessage() {}

func (x *PossessResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PossessResultResponse.ProtoReflect.Descriptor instead.
func (*PossessResultResponse) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{11}
}

func (x *PossessResultResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PossessResultResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PossessResultResponse) GetIsPublicEnemy() bool {
	if x != nil {
		return x.IsPublicEnemy
	}
	return false
}

func (x *PossessResultResponse) GetForceBeast() bool {
	if x != nil {
		return x.ForceBeast
	}
	return false
}

func (x *PossessResultResponse) GetPossessCount() int32 {
	if x != nil {
		return x.PossessCount
	}
	return 0
}

func (x *PossessResultResponse) GetPlunderedShen() int32 {
	if x != nil {
		return x.PlunderedShen
	}
	return 0
}

func (x *PossessResultResponse) GetMustReincarnate() bool {
	if x != nil {
		return x.MustReincarnate
	}
	return false
}

// 兽身化形切换
type BeastTransformRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ToHuman       bool                   `protobuf:"varint,2,opt,name=to_human,json=toHuman,proto3" json:"to_human,omitempty"` // true=化为人形 false=变为兽形
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeastTransformRequest) Reset() {
	*x = BeastTransformRequest{}
	mi := &file_death_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeastTransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeastTransformRequest) ProtoMessage() {}

func (x *BeastTransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeastTransformRequest.ProtoReflect.Descriptor instead.
func (*BeastTransformRequest) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{12}
}

func (x *BeastTransformRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *BeastTransformRequest) GetToHuman() bool {
	if x != nil {
		return x.ToHuman
	}
	return false
}

type BeastTransformResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg            string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	CurrentForm    int32                  `protobuf:"varint,3,opt,name=current_form,json=currentForm,proto3" json:"current_form,omitempty"`           // 1=兽形 2=人形
	JingMultiplier float64                `protobuf:"fixed64,4,opt,name=jing_multiplier,json=jingMultiplier,proto3" json:"jing_multiplier,omitempty"` // 1.5 or 1.0
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BeastTransformResponse) Reset() {
	*x = BeastTransformResponse{}
	mi := &file_death_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeastTransformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeastTransformResponse) ProtoMessage() {}

func (x *BeastTransformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeastTransformResponse.ProtoReflect.Descriptor instead.
func (*BeastTransformResponse) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{13}
}

func (x *BeastTransformResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BeastTransformResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BeastTransformResponse) GetCurrentForm() int32 {
	if x != nil {
		return x.CurrentForm
	}
	return 0
}

func (x *BeastTransformResponse) GetJingMultiplier() float64 {
	if x != nil {
		return x.JingMultiplier
	}
	return 0
}

// 创建遗迹洞府
type RuinsCreateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CharacterId      int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	LocationX        int32                  `protobuf:"varint,2,opt,name=location_x,json=locationX,proto3" json:"location_x,omitempty"`
	LocationY        int32                  `protobuf:"varint,3,opt,name=location_y,json=locationY,proto3" json:"location_y,omitempty"`
	TotalWealth      int64                  `protobuf:"varint,4,opt,name=total_wealth,json=totalWealth,proto3" json:"total_wealth,omitempty"`
	RestrictionLevel int32                  `protobuf:"varint,5,opt,name=restriction_level,json=restrictionLevel,proto3" json:"restriction_level,omitempty"` // 禁制等级 0-9
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RuinsCreateRequest) Reset() {
	*x = RuinsCreateRequest{}
	mi := &file_death_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuinsCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuinsCreateRequest) ProtoMessage() {}

func (x *RuinsCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuinsCreateRequest.ProtoReflect.Descriptor instead.
func (*RuinsCreateRequest) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{14}
}

func (x *RuinsCreateRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *RuinsCreateRequest) GetLocationX() int32 {
	if x != nil {
		return x.LocationX
	}
	return 0
}

func (x *RuinsCreateRequest) GetLocationY() int32 {
	if x != nil {
		return x.LocationY
	}
	return 0
}

func (x *RuinsCreateRequest) GetTotalWealth() int64 {
	if x != nil {
		return x.TotalWealth
	}
	return 0
}

func (x *RuinsCreateRequest) GetRestrictionLevel() int32 {
	if x != nil {
		return x.RestrictionLevel
	}
	return 0
}

type RuinsCreateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg              string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	RuinId           int64                  `protobuf:"varint,3,opt,name=ruin_id,json=ruinId,proto3" json:"ruin_id,omitempty"`
	RestrictionLevel int32                  `protobuf:"varint,4,opt,name=restriction_level,json=restrictionLevel,proto3" json:"restriction_level,omitempty"`
	ExpiresInDays    int32                  `protobuf:"varint,5,opt,name=expires_in_days,json=expiresInDays,proto3" json:"expires_in_days,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RuinsCreateResponse) Reset() {
	*x = RuinsCreateResponse{}
	mi := &file_death_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuinsCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuinsCreateResponse) ProtoMessage() {}

func (x *RuinsCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuinsCreateResponse.ProtoReflect.Descriptor instead.
func (*RuinsCreateResponse) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{15}
}

func (x *RuinsCreateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RuinsCreateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RuinsCreateResponse) GetRuinId() int64 {
	if x != nil {
		return x.RuinId
	}
	return 0
}

func (x *RuinsCreateResponse) GetRestrictionLevel() int32 {
	if x != nil {
		return x.RestrictionLevel
	}
	return 0
}

func (x *RuinsCreateResponse) GetExpiresInDays() int32 {
	if x != nil {
		return x.ExpiresInDays
	}
	return 0
}

// 继承遗迹洞府
type RuinsInheritRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuinId        int64                  `protobuf:"varint,1,opt,name=ruin_id,json=ruinId,proto3" json:"ruin_id,omitempty"`
	CharacterId   int64                  `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	BreakLevel    int32                  `protobuf:"varint,3,opt,name=break_level,json=breakLevel,proto3" json:"break_level,omitempty"` // 尝试突破的禁制等级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuinsInheritRequest) Reset() {
	*x = RuinsInheritRequest{}
	mi := &file_death_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuinsInheritRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuinsInheritRequest) ProtoMessage() {}

func (x *RuinsInheritRequest) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuinsInheritRequest.ProtoReflect.Descriptor instead.
func (*RuinsInheritRequest) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{16}
}

func (x *RuinsInheritRequest) GetRuinId() int64 {
	if x != nil {
		return x.RuinId
	}
	return 0
}

func (x *RuinsInheritRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *RuinsInheritRequest) GetBreakLevel() int32 {
	if x != nil {
		return x.BreakLevel
	}
	return 0
}

type RuinsInheritResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuinsInheritResponse) Reset() {
	*x = RuinsInheritResponse{}
	mi := &file_death_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuinsInheritResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuinsInheritResponse) ProtoMessage() {}

func (x *RuinsInheritResponse) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuinsInheritResponse.ProtoReflect.Descriptor instead.
func (*RuinsInheritResponse) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{17}
}

func (x *RuinsInheritResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RuinsInheritResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 查询公敌状态
type PublicEnemyStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicEnemyStatusRequest) Reset() {
	*x = PublicEnemyStatusRequest{}
	mi := &file_death_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicEnemyStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicEnemyStatusRequest) ProtoMessage() {}

func (x *PublicEnemyStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicEnemyStatusRequest.ProtoReflect.Descriptor instead.
func (*PublicEnemyStatusRequest) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{18}
}

func (x *PublicEnemyStatusRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type PublicEnemyStatusResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Code                    int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                     string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	IsPublicEnemy           bool                   `protobuf:"varint,3,opt,name=is_public_enemy,json=isPublicEnemy,proto3" json:"is_public_enemy,omitempty"`
	Reason                  int32                  `protobuf:"varint,4,opt,name=reason,proto3" json:"reason,omitempty"`
	BountyTotal             int64                  `protobuf:"varint,5,opt,name=bounty_total,json=bountyTotal,proto3" json:"bounty_total,omitempty"`
	ThunderCount            int32                  `protobuf:"varint,6,opt,name=thunder_count,json=thunderCount,proto3" json:"thunder_count,omitempty"`
	NextThunderAt           string                 `protobuf:"bytes,7,opt,name=next_thunder_at,json=nextThunderAt,proto3" json:"next_thunder_at,omitempty"`
	ThunderRemainingSeconds int32                  `protobuf:"varint,8,opt,name=thunder_remaining_seconds,json=thunderRemainingSeconds,proto3" json:"thunder_remaining_seconds,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PublicEnemyStatusResponse) Reset() {
	*x = PublicEnemyStatusResponse{}
	mi := &file_death_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicEnemyStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicEnemyStatusResponse) ProtoMessage() {}

func (x *PublicEnemyStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicEnemyStatusResponse.ProtoReflect.Descriptor instead.
func (*PublicEnemyStatusResponse) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{19}
}

func (x *PublicEnemyStatusResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PublicEnemyStatusResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PublicEnemyStatusResponse) GetIsPublicEnemy() bool {
	if x != nil {
		return x.IsPublicEnemy
	}
	return false
}

func (x *PublicEnemyStatusResponse) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *PublicEnemyStatusResponse) GetBountyTotal() int64 {
	if x != nil {
		return x.BountyTotal
	}
	return 0
}

func (x *PublicEnemyStatusResponse) GetThunderCount() int32 {
	if x != nil {
		return x.ThunderCount
	}
	return 0
}

func (x *PublicEnemyStatusResponse) GetNextThunderAt() string {
	if x != nil {
		return x.NextThunderAt
	}
	return ""
}

func (x *PublicEnemyStatusResponse) GetThunderRemainingSeconds() int32 {
	if x != nil {
		return x.ThunderRemainingSeconds
	}
	return 0
}

type BaseAttrs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jing          int32                  `protobuf:"varint,1,opt,name=jing,proto3" json:"jing,omitempty"`
	Qi            int32                  `protobuf:"varint,2,opt,name=qi,proto3" json:"qi,omitempty"`
	Shen          int32                  `protobuf:"varint,3,opt,name=shen,proto3" json:"shen,omitempty"`
	QiYun         int32                  `protobuf:"varint,4,opt,name=qi_yun,json=qiYun,proto3" json:"qi_yun,omitempty"`
	WuXing        int32                  `protobuf:"varint,5,opt,name=wu_xing,json=wuXing,proto3" json:"wu_xing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseAttrs) Reset() {
	*x = BaseAttrs{}
	mi := &file_death_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseAttrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseAttrs) ProtoMessage() {}

func (x *BaseAttrs) ProtoReflect() protoreflect.Message {
	mi := &file_death_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseAttrs.ProtoReflect.Descriptor instead.
func (*BaseAttrs) Descriptor() ([]byte, []int) {
	return file_death_proto_rawDescGZIP(), []int{20}
}

func (x *BaseAttrs) GetJing() int32 {
	if x != nil {
		return x.Jing
	}
	return 0
}

func (x *BaseAttrs) GetQi() int32 {
	if x != nil {
		return x.Qi
	}
	return 0
}

func (x *BaseAttrs) GetShen() int32 {
	if x != nil {
		return x.Shen
	}
	return 0
}

func (x *BaseAttrs) GetQiYun() int32 {
	if x != nil {
		return x.QiYun
	}
	return 0
}

func (x *BaseAttrs) GetWuXing() int32 {
	if x != nil {
		return x.WuXing
	}
	return 0
}

var File_death_proto protoreflect.FileDescriptor

const file_death_proto_rawDesc = "" +
	"\n" +
	"\vdeath.proto\x12\rxunxian.death\"\xb4\x01\n" +
	"\x13DeathTriggerRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\x12\x1d\n" +
	"\n" +
	"death_type\x18\x02 \x01(\x05R\tdeathType\x12\x1d\n" +
	"\n" +
	"is_dungeon\x18\x03 \x01(\bR\tisDungeon\x12\x1d\n" +
	"\n" +
	"location_x\x18\x04 \x01(\x05R\tlocationX\x12\x1d\n" +
	"\n" +
	"location_y\x18\x05 \x01(\x05R\tlocationY\"\x80\x01\n" +
	"\x14DeathTriggerResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x10is_dungeon_death\x18\x03 \x01(\bR\x0eisDungeonDeath\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\"Z\n" +
	"\x14ReincarnationRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\x12\x1f\n" +
	"\vforce_beast\x18\x02 \x01(\bR\n" +
	"forceBeast\"\xed\x01\n" +
	"\x15ReincarnationResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12-\n" +
	"\x12reincarnation_type\x18\x03 \x01(\x05R\x11reincarnationType\x12-\n" +
	"\x12reincarnation_name\x18\x04 \x01(\tR\x11reincarnationName\x125\n" +
	"\tnew_attrs\x18\x05 \x01(\v2\x18.xunxian.death.BaseAttrsR\bnewAttrs\x12\x19\n" +
	"\bis_beast\x18\x06 \x01(\bR\aisBeast\"6\n" +
	"\x11GhostEnterRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\"\xa1\x01\n" +
	"\x12GhostEnterResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1d\n" +
	"\n" +
	"ghost_mode\x18\x03 \x01(\x05R\tghostMode\x12\x1e\n" +
	"\vsoul_hp_max\x18\x04 \x01(\x05R\tsoulHpMax\x12&\n" +
	"\x0fsoul_hp_current\x18\x05 \x01(\x05R\rsoulHpCurrent\"5\n" +
	"\x10GhostExitRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\"9\n" +
	"\x11GhostExitResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x97\x01\n" +
	"\x13PossessStartRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\x05R\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\x12\x1f\n" +
	"\vtarget_name\x18\x04 \x01(\tR\n" +
	"targetName\"\xc1\x01\n" +
	"\x14PossessStartResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x01R\vsuccessRate\x12%\n" +
	"\x0epossessor_shen\x18\x05 \x01(\x05R\rpossessorShen\x12\x1f\n" +
	"\vtarget_shen\x18\x06 \x01(\x05R\n" +
	"targetShen\"p\n" +
	"\x14PossessResultRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\"\xfd\x01\n" +
	"\x15PossessResultResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12&\n" +
	"\x0fis_public_enemy\x18\x03 \x01(\bR\risPublicEnemy\x12\x1f\n" +
	"\vforce_beast\x18\x04 \x01(\bR\n" +
	"forceBeast\x12#\n" +
	"\rpossess_count\x18\x05 \x01(\x05R\fpossessCount\x12%\n" +
	"\x0eplundered_shen\x18\x06 \x01(\x05R\rplunderedShen\x12)\n" +
	"\x10must_reincarnate\x18\a \x01(\bR\x0fmustReincarnate\"U\n" +
	"\x15BeastTransformRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\x12\x19\n" +
	"\bto_human\x18\x02 \x01(\bR\atoHuman\"\x8a\x01\n" +
	"\x16BeastTransformResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12!\n" +
	"\fcurrent_form\x18\x03 \x01(\x05R\vcurrentForm\x12'\n" +
	"\x0fjing_multiplier\x18\x04 \x01(\x01R\x0ejingMultiplier\"\xc5\x01\n" +
	"\x12RuinsCreateRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\x12\x1d\n" +
	"\n" +
	"location_x\x18\x02 \x01(\x05R\tlocationX\x12\x1d\n" +
	"\n" +
	"location_y\x18\x03 \x01(\x05R\tlocationY\x12!\n" +
	"\ftotal_wealth\x18\x04 \x01(\x03R\vtotalWealth\x12+\n" +
	"\x11restriction_level\x18\x05 \x01(\x05R\x10restrictionLevel\"\xa9\x01\n" +
	"\x13RuinsCreateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x17\n" +
	"\aruin_id\x18\x03 \x01(\x03R\x06ruinId\x12+\n" +
	"\x11restriction_level\x18\x04 \x01(\x05R\x10restrictionLevel\x12&\n" +
	"\x0fexpires_in_days\x18\x05 \x01(\x05R\rexpiresInDays\"r\n" +
	"\x13RuinsInheritRequest\x12\x17\n" +
	"\aruin_id\x18\x01 \x01(\x03R\x06ruinId\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\x03R\vcharacterId\x12\x1f\n" +
	"\vbreak_level\x18\x03 \x01(\x05R\n" +
	"breakLevel\"<\n" +
	"\x14RuinsInheritResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"=\n" +
	"\x18PublicEnemyStatusRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\"\xad\x02\n" +
	"\x19PublicEnemyStatusResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12&\n" +
	"\x0fis_public_enemy\x18\x03 \x01(\bR\risPublicEnemy\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\x05R\x06reason\x12!\n" +
	"\fbounty_total\x18\x05 \x01(\x03R\vbountyTotal\x12#\n" +
	"\rthunder_count\x18\x06 \x01(\x05R\fthunderCount\x12&\n" +
	"\x0fnext_thunder_at\x18\a \x01(\tR\rnextThunderAt\x12:\n" +
	"\x19thunder_remaining_seconds\x18\b \x01(\x05R\x17thunderRemainingSeconds\"s\n" +
	"\tBaseAttrs\x12\x12\n" +
	"\x04jing\x18\x01 \x01(\x05R\x04jing\x12\x0e\n" +
	"\x02qi\x18\x02 \x01(\x05R\x02qi\x12\x12\n" +
	"\x04shen\x18\x03 \x01(\x05R\x04shen\x12\x15\n" +
	"\x06qi_yun\x18\x04 \x01(\x05R\x05qiYun\x12\x17\n" +
	"\awu_xing\x18\x05 \x01(\x05R\x06wuXingB\x15Z\x13xunxian/proto/deathb\x06proto3"

var (
	file_death_proto_rawDescOnce sync.Once
	file_death_proto_rawDescData []byte
)

func file_death_proto_rawDescGZIP() []byte {
	file_death_proto_rawDescOnce.Do(func() {
		file_death_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_death_proto_rawDesc), len(file_death_proto_rawDesc)))
	})
	return file_death_proto_rawDescData
}

var file_death_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_death_proto_goTypes = []any{
	(*DeathTriggerRequest)(nil),       // 0: xunxian.death.DeathTriggerRequest
	(*DeathTriggerResponse)(nil),      // 1: xunxian.death.DeathTriggerResponse
	(*ReincarnationRequest)(nil),      // 2: xunxian.death.ReincarnationRequest
	(*ReincarnationResponse)(nil),     // 3: xunxian.death.ReincarnationResponse
	(*GhostEnterRequest)(nil),         // 4: xunxian.death.GhostEnterRequest
	(*GhostEnterResponse)(nil),        // 5: xunxian.death.GhostEnterResponse
	(*GhostExitRequest)(nil),          // 6: xunxian.death.GhostExitRequest
	(*GhostExitResponse)(nil),         // 7: xunxian.death.GhostExitResponse
	(*PossessStartRequest)(nil),       // 8: xunxian.death.PossessStartRequest
	(*PossessStartResponse)(nil),      // 9: xunxian.death.PossessStartResponse
	(*PossessResultRequest)(nil),      // 10: xunxian.death.PossessResultRequest
	(*PossessResultResponse)(nil),     // 11: xunxian.death.PossessResultResponse
	(*BeastTransformRequest)(nil),     // 12: xunxian.death.BeastTransformRequest
	(*BeastTransformResponse)(nil),    // 13: xunxian.death.BeastTransformResponse
	(*RuinsCreateRequest)(nil),        // 14: xunxian.death.RuinsCreateRequest
	(*RuinsCreateResponse)(nil),       // 15: xunxian.death.RuinsCreateResponse
	(*RuinsInheritRequest)(nil),       // 16: xunxian.death.RuinsInheritRequest
	(*RuinsInheritResponse)(nil),      // 17: xunxian.death.RuinsInheritResponse
	(*PublicEnemyStatusRequest)(nil),  // 18: xunxian.death.PublicEnemyStatusRequest
	(*PublicEnemyStatusResponse)(nil), // 19: xunxian.death.PublicEnemyStatusResponse
	(*BaseAttrs)(nil),                 // 20: xunxian.death.BaseAttrs
}
var file_death_proto_depIdxs = []int32{
	20, // 0: xunxian.death.ReincarnationResponse.new_attrs:type_name -> xunxian.death.BaseAttrs
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_death_proto_init() }
func file_death_proto_init() {
	if File_death_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_death_proto_rawDesc), len(file_death_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_death_proto_goTypes,
		DependencyIndexes: file_death_proto_depIdxs,
		MessageInfos:      file_death_proto_msgTypes,
	}.Build()
	File_death_proto = out.File
	file_death_proto_goTypes = nil
	file_death_proto_depIdxs = nil
}
