// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: character.proto

package character

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建角色
type CreateCharRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`      // 2-8汉字角色名
	Gender        int32                  `protobuf:"varint,2,opt,name=gender,proto3" json:"gender,omitempty"` // 1=男 2=女
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharRequest) Reset() {
	*x = CreateCharRequest{}
	mi := &file_character_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharRequest) ProtoMessage() {}

func (x *CreateCharRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharRequest.ProtoReflect.Descriptor instead.
func (*CreateCharRequest) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCharRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCharRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

type CreateCharResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	CharacterId   int64                  `protobuf:"varint,3,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Gender        int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Race          int32                  `protobuf:"varint,6,opt,name=race,proto3" json:"race,omitempty"`
	Attrs         *CharacterAttrs        `protobuf:"bytes,7,opt,name=attrs,proto3" json:"attrs,omitempty"`
	Realm         *RealmInfo             `protobuf:"bytes,8,opt,name=realm,proto3" json:"realm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharResponse) Reset() {
	*x = CreateCharResponse{}
	mi := &file_character_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharResponse) ProtoMessage() {}

func (x *CreateCharResponse) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharResponse.ProtoReflect.Descriptor instead.
func (*CreateCharResponse) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCharResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateCharResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateCharResponse) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *CreateCharResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCharResponse) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *CreateCharResponse) GetRace() int32 {
	if x != nil {
		return x.Race
	}
	return 0
}

func (x *CreateCharResponse) GetAttrs() *CharacterAttrs {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *CreateCharResponse) GetRealm() *RealmInfo {
	if x != nil {
		return x.Realm
	}
	return nil
}

// 查询角色完整信息
type GetCharInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharInfoRequest) Reset() {
	*x = GetCharInfoRequest{}
	mi := &file_character_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharInfoRequest) ProtoMessage() {}

func (x *GetCharInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharInfoRequest.ProtoReflect.Descriptor instead.
func (*GetCharInfoRequest) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{2}
}

func (x *GetCharInfoRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type GetCharInfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg              string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Base             *CharacterBase         `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
	Attrs            *CharacterAttrs        `protobuf:"bytes,4,opt,name=attrs,proto3" json:"attrs,omitempty"`
	Derived          *DerivedAttrs          `protobuf:"bytes,5,opt,name=derived,proto3" json:"derived,omitempty"`
	Realm            *RealmInfo             `protobuf:"bytes,6,opt,name=realm,proto3" json:"realm,omitempty"`
	QiElements       []*QiElement           `protobuf:"bytes,7,rep,name=qi_elements,json=qiElements,proto3" json:"qi_elements,omitempty"`
	ElementCount     int32                  `protobuf:"varint,8,opt,name=element_count,json=elementCount,proto3" json:"element_count,omitempty"`
	ExpMultiplier    float64                `protobuf:"fixed64,9,opt,name=exp_multiplier,json=expMultiplier,proto3" json:"exp_multiplier,omitempty"`
	DamageMultiplier float64                `protobuf:"fixed64,10,opt,name=damage_multiplier,json=damageMultiplier,proto3" json:"damage_multiplier,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetCharInfoResponse) Reset() {
	*x = GetCharInfoResponse{}
	mi := &file_character_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharInfoResponse) ProtoMessage() {}

func (x *GetCharInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharInfoResponse.ProtoReflect.Descriptor instead.
func (*GetCharInfoResponse) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{3}
}

func (x *GetCharInfoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCharInfoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetCharInfoResponse) GetBase() *CharacterBase {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *GetCharInfoResponse) GetAttrs() *CharacterAttrs {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *GetCharInfoResponse) GetDerived() *DerivedAttrs {
	if x != nil {
		return x.Derived
	}
	return nil
}

func (x *GetCharInfoResponse) GetRealm() *RealmInfo {
	if x != nil {
		return x.Realm
	}
	return nil
}

func (x *GetCharInfoResponse) GetQiElements() []*QiElement {
	if x != nil {
		return x.QiElements
	}
	return nil
}

func (x *GetCharInfoResponse) GetElementCount() int32 {
	if x != nil {
		return x.ElementCount
	}
	return 0
}

func (x *GetCharInfoResponse) GetExpMultiplier() float64 {
	if x != nil {
		return x.ExpMultiplier
	}
	return 0
}

func (x *GetCharInfoResponse) GetDamageMultiplier() float64 {
	if x != nil {
		return x.DamageMultiplier
	}
	return 0
}

// 查询五维属性及衍生值
type GetCharAttrsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharAttrsRequest) Reset() {
	*x = GetCharAttrsRequest{}
	mi := &file_character_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharAttrsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharAttrsRequest) ProtoMessage() {}

func (x *GetCharAttrsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharAttrsRequest.ProtoReflect.Descriptor instead.
func (*GetCharAttrsRequest) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{4}
}

func (x *GetCharAttrsRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type GetCharAttrsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	BaseAttrs     *BaseAttrs             `protobuf:"bytes,3,opt,name=base_attrs,json=baseAttrs,proto3" json:"base_attrs,omitempty"`
	Current       *CurrentAttrs          `protobuf:"bytes,4,opt,name=current,proto3" json:"current,omitempty"`
	Derived       *DerivedAttrs          `protobuf:"bytes,5,opt,name=derived,proto3" json:"derived,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharAttrsResponse) Reset() {
	*x = GetCharAttrsResponse{}
	mi := &file_character_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharAttrsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharAttrsResponse) ProtoMessage() {}

func (x *GetCharAttrsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharAttrsResponse.ProtoReflect.Descriptor instead.
func (*GetCharAttrsResponse) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{5}
}

func (x *GetCharAttrsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCharAttrsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetCharAttrsResponse) GetBaseAttrs() *BaseAttrs {
	if x != nil {
		return x.BaseAttrs
	}
	return nil
}

func (x *GetCharAttrsResponse) GetCurrent() *CurrentAttrs {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *GetCharAttrsResponse) GetDerived() *DerivedAttrs {
	if x != nil {
		return x.Derived
	}
	return nil
}

// 增加经验
type AddExpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ExpJing       int64                  `protobuf:"varint,2,opt,name=exp_jing,json=expJing,proto3" json:"exp_jing,omitempty"` // 精属性经验
	ExpQi         int64                  `protobuf:"varint,3,opt,name=exp_qi,json=expQi,proto3" json:"exp_qi,omitempty"`       // 气属性经验
	ExpShen       int64                  `protobuf:"varint,4,opt,name=exp_shen,json=expShen,proto3" json:"exp_shen,omitempty"` // 神属性经验
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddExpRequest) Reset() {
	*x = AddExpRequest{}
	mi := &file_character_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddExpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddExpRequest) ProtoMessage() {}

func (x *AddExpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddExpRequest.ProtoReflect.Descriptor instead.
func (*AddExpRequest) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{6}
}

func (x *AddExpRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *AddExpRequest) GetExpJing() int64 {
	if x != nil {
		return x.ExpJing
	}
	return 0
}

func (x *AddExpRequest) GetExpQi() int64 {
	if x != nil {
		return x.ExpQi
	}
	return 0
}

func (x *AddExpRequest) GetExpShen() int64 {
	if x != nil {
		return x.ExpShen
	}
	return 0
}

type AddExpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ExpJing       int64                  `protobuf:"varint,3,opt,name=exp_jing,json=expJing,proto3" json:"exp_jing,omitempty"`
	ExpQi         int64                  `protobuf:"varint,4,opt,name=exp_qi,json=expQi,proto3" json:"exp_qi,omitempty"`
	ExpShen       int64                  `protobuf:"varint,5,opt,name=exp_shen,json=expShen,proto3" json:"exp_shen,omitempty"`
	ExpReq        int64                  `protobuf:"varint,6,opt,name=exp_req,json=expReq,proto3" json:"exp_req,omitempty"`
	CanUpgrade    bool                   `protobuf:"varint,7,opt,name=can_upgrade,json=canUpgrade,proto3" json:"can_upgrade,omitempty"`
	Multiplier    float64                `protobuf:"fixed64,8,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddExpResponse) Reset() {
	*x = AddExpResponse{}
	mi := &file_character_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddExpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddExpResponse) ProtoMessage() {}

func (x *AddExpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddExpResponse.ProtoReflect.Descriptor instead.
func (*AddExpResponse) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{7}
}

func (x *AddExpResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddExpResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AddExpResponse) GetExpJing() int64 {
	if x != nil {
		return x.ExpJing
	}
	return 0
}

func (x *AddExpResponse) GetExpQi() int64 {
	if x != nil {
		return x.ExpQi
	}
	return 0
}

func (x *AddExpResponse) GetExpShen() int64 {
	if x != nil {
		return x.ExpShen
	}
	return 0
}

func (x *AddExpResponse) GetExpReq() int64 {
	if x != nil {
		return x.ExpReq
	}
	return 0
}

func (x *AddExpResponse) GetCanUpgrade() bool {
	if x != nil {
		return x.CanUpgrade
	}
	return false
}

func (x *AddExpResponse) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

// 境界升级（小阶）
type RealmUpgradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealmUpgradeRequest) Reset() {
	*x = RealmUpgradeRequest{}
	mi := &file_character_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealmUpgradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealmUpgradeRequest) ProtoMessage() {}

func (x *RealmUpgradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealmUpgradeRequest.ProtoReflect.Descriptor instead.
func (*RealmUpgradeRequest) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{8}
}

func (x *RealmUpgradeRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type RealmUpgradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	MajorStage    int32                  `protobuf:"varint,3,opt,name=major_stage,json=majorStage,proto3" json:"major_stage,omitempty"`
	MinorStage    int32                  `protobuf:"varint,4,opt,name=minor_stage,json=minorStage,proto3" json:"minor_stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealmUpgradeResponse) Reset() {
	*x = RealmUpgradeResponse{}
	mi := &file_character_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealmUpgradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealmUpgradeResponse) ProtoMessage() {}

func (x *RealmUpgradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealmUpgradeResponse.ProtoReflect.Descriptor instead.
func (*RealmUpgradeResponse) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{9}
}

func (x *RealmUpgradeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RealmUpgradeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RealmUpgradeResponse) GetMajorStage() int32 {
	if x != nil {
		return x.MajorStage
	}
	return 0
}

func (x *RealmUpgradeResponse) GetMinorStage() int32 {
	if x != nil {
		return x.MinorStage
	}
	return 0
}

// 境界突破（大境界）
type BreakthroughRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreakthroughRequest) Reset() {
	*x = BreakthroughRequest{}
	mi := &file_character_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreakthroughRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakthroughRequest) ProtoMessage() {}

func (x *BreakthroughRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakthroughRequest.ProtoReflect.Descriptor instead.
func (*BreakthroughRequest) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{10}
}

func (x *BreakthroughRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type BreakthroughResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // success / xinmo_fail / tribulation_fail
	MajorStage    int32                  `protobuf:"varint,4,opt,name=major_stage,json=majorStage,proto3" json:"major_stage,omitempty"`
	MinorStage    int32                  `protobuf:"varint,5,opt,name=minor_stage,json=minorStage,proto3" json:"minor_stage,omitempty"`
	StageName     string                 `protobuf:"bytes,6,opt,name=stage_name,json=stageName,proto3" json:"stage_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreakthroughResponse) Reset() {
	*x = BreakthroughResponse{}
	mi := &file_character_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreakthroughResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreakthroughResponse) ProtoMessage() {}

func (x *BreakthroughResponse) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreakthroughResponse.ProtoReflect.Descriptor instead.
func (*BreakthroughResponse) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{11}
}

func (x *BreakthroughResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BreakthroughResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BreakthroughResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *BreakthroughResponse) GetMajorStage() int32 {
	if x != nil {
		return x.MajorStage
	}
	return 0
}

func (x *BreakthroughResponse) GetMinorStage() int32 {
	if x != nil {
		return x.MinorStage
	}
	return 0
}

func (x *BreakthroughResponse) GetStageName() string {
	if x != nil {
		return x.StageName
	}
	return ""
}

// 修炼五行属性
type QiCultivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	ElementType   int32                  `protobuf:"varint,2,opt,name=element_type,json=elementType,proto3" json:"element_type,omitempty"` // 1=金 2=木 3=水 4=火 5=土
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QiCultivateRequest) Reset() {
	*x = QiCultivateRequest{}
	mi := &file_character_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QiCultivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QiCultivateRequest) ProtoMessage() {}

func (x *QiCultivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QiCultivateRequest.ProtoReflect.Descriptor instead.
func (*QiCultivateRequest) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{12}
}

func (x *QiCultivateRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *QiCultivateRequest) GetElementType() int32 {
	if x != nil {
		return x.ElementType
	}
	return 0
}

type QiCultivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	ElementType   int32                  `protobuf:"varint,3,opt,name=element_type,json=elementType,proto3" json:"element_type,omitempty"`
	ElementName   string                 `protobuf:"bytes,4,opt,name=element_name,json=elementName,proto3" json:"element_name,omitempty"`
	ElementCount  int32                  `protobuf:"varint,5,opt,name=element_count,json=elementCount,proto3" json:"element_count,omitempty"`
	ExpMultiplier float64                `protobuf:"fixed64,6,opt,name=exp_multiplier,json=expMultiplier,proto3" json:"exp_multiplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QiCultivateResponse) Reset() {
	*x = QiCultivateResponse{}
	mi := &file_character_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QiCultivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QiCultivateResponse) ProtoMessage() {}

func (x *QiCultivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QiCultivateResponse.ProtoReflect.Descriptor instead.
func (*QiCultivateResponse) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{13}
}

func (x *QiCultivateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QiCultivateResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *QiCultivateResponse) GetElementType() int32 {
	if x != nil {
		return x.ElementType
	}
	return 0
}

func (x *QiCultivateResponse) GetElementName() string {
	if x != nil {
		return x.ElementName
	}
	return ""
}

func (x *QiCultivateResponse) GetElementCount() int32 {
	if x != nil {
		return x.ElementCount
	}
	return 0
}

func (x *QiCultivateResponse) GetExpMultiplier() float64 {
	if x != nil {
		return x.ExpMultiplier
	}
	return 0
}

// 查询已修属性
type GetQiElementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQiElementsRequest) Reset() {
	*x = GetQiElementsRequest{}
	mi := &file_character_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQiElementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQiElementsRequest) ProtoMessage() {}

func (x *GetQiElementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQiElementsRequest.ProtoReflect.Descriptor instead.
func (*GetQiElementsRequest) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{14}
}

func (x *GetQiElementsRequest) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type GetQiElementsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg              string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Elements         []*QiElement           `protobuf:"bytes,3,rep,name=elements,proto3" json:"elements,omitempty"`
	ElementCount     int32                  `protobuf:"varint,4,opt,name=element_count,json=elementCount,proto3" json:"element_count,omitempty"`
	ExpMultiplier    float64                `protobuf:"fixed64,5,opt,name=exp_multiplier,json=expMultiplier,proto3" json:"exp_multiplier,omitempty"`
	DamageMultiplier float64                `protobuf:"fixed64,6,opt,name=damage_multiplier,json=damageMultiplier,proto3" json:"damage_multiplier,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetQiElementsResponse) Reset() {
	*x = GetQiElementsResponse{}
	mi := &file_character_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQiElementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQiElementsResponse) ProtoMessage() {}

func (x *GetQiElementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQiElementsResponse.ProtoReflect.Descriptor instead.
func (*GetQiElementsResponse) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{15}
}

func (x *GetQiElementsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetQiElementsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetQiElementsResponse) GetElements() []*QiElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *GetQiElementsResponse) GetElementCount() int32 {
	if x != nil {
		return x.ElementCount
	}
	return 0
}

func (x *GetQiElementsResponse) GetExpMultiplier() float64 {
	if x != nil {
		return x.ExpMultiplier
	}
	return 0
}

func (x *GetQiElementsResponse) GetDamageMultiplier() float64 {
	if x != nil {
		return x.DamageMultiplier
	}
	return 0
}

type CharacterBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   int64                  `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Gender        int32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`                        // 1=男 2=女
	Race          int32                  `protobuf:"varint,5,opt,name=race,proto3" json:"race,omitempty"`                            // 1=人族 2=鬼修 3=兽身
	FormState     int32                  `protobuf:"varint,6,opt,name=form_state,json=formState,proto3" json:"form_state,omitempty"` // 1=人形 2=兽形
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterBase) Reset() {
	*x = CharacterBase{}
	mi := &file_character_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterBase) ProtoMessage() {}

func (x *CharacterBase) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterBase.ProtoReflect.Descriptor instead.
func (*CharacterBase) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{16}
}

func (x *CharacterBase) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *CharacterBase) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CharacterBase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterBase) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *CharacterBase) GetRace() int32 {
	if x != nil {
		return x.Race
	}
	return 0
}

func (x *CharacterBase) GetFormState() int32 {
	if x != nil {
		return x.FormState
	}
	return 0
}

type CharacterAttrs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jing          int32                  `protobuf:"varint,1,opt,name=jing,proto3" json:"jing,omitempty"`                                   // 精（肉身强度）
	Qi            int32                  `protobuf:"varint,2,opt,name=qi,proto3" json:"qi,omitempty"`                                       // 气（修炼能量总和）
	Shen          int32                  `protobuf:"varint,3,opt,name=shen,proto3" json:"shen,omitempty"`                                   // 神（灵魂之力）
	QiYun         int32                  `protobuf:"varint,4,opt,name=qi_yun,json=qiYun,proto3" json:"qi_yun,omitempty"`                    // 气运（命运属性）
	WuXing        int32                  `protobuf:"varint,5,opt,name=wu_xing,json=wuXing,proto3" json:"wu_xing,omitempty"`                 // 悟性（成长天赋）
	HpMax         int32                  `protobuf:"varint,6,opt,name=hp_max,json=hpMax,proto3" json:"hp_max,omitempty"`                    // 气血上限
	HpCurrent     int32                  `protobuf:"varint,7,opt,name=hp_current,json=hpCurrent,proto3" json:"hp_current,omitempty"`        // 当前气血
	MpMax         int32                  `protobuf:"varint,8,opt,name=mp_max,json=mpMax,proto3" json:"mp_max,omitempty"`                    // 灵力上限
	MpCurrent     int32                  `protobuf:"varint,9,opt,name=mp_current,json=mpCurrent,proto3" json:"mp_current,omitempty"`        // 当前灵力
	SoulMax       int32                  `protobuf:"varint,10,opt,name=soul_max,json=soulMax,proto3" json:"soul_max,omitempty"`             // 魂力上限（鬼修专用）
	SoulCurrent   int32                  `protobuf:"varint,11,opt,name=soul_current,json=soulCurrent,proto3" json:"soul_current,omitempty"` // 当前魂力
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterAttrs) Reset() {
	*x = CharacterAttrs{}
	mi := &file_character_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterAttrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterAttrs) ProtoMessage() {}

func (x *CharacterAttrs) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterAttrs.ProtoReflect.Descriptor instead.
func (*CharacterAttrs) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{17}
}

func (x *CharacterAttrs) GetJing() int32 {
	if x != nil {
		return x.Jing
	}
	return 0
}

func (x *CharacterAttrs) GetQi() int32 {
	if x != nil {
		return x.Qi
	}
	return 0
}

func (x *CharacterAttrs) GetShen() int32 {
	if x != nil {
		return x.Shen
	}
	return 0
}

func (x *CharacterAttrs) GetQiYun() int32 {
	if x != nil {
		return x.QiYun
	}
	return 0
}

func (x *CharacterAttrs) GetWuXing() int32 {
	if x != nil {
		return x.WuXing
	}
	return 0
}

func (x *CharacterAttrs) GetHpMax() int32 {
	if x != nil {
		return x.HpMax
	}
	return 0
}

func (x *CharacterAttrs) GetHpCurrent() int32 {
	if x != nil {
		return x.HpCurrent
	}
	return 0
}

func (x *CharacterAttrs) GetMpMax() int32 {
	if x != nil {
		return x.MpMax
	}
	return 0
}

func (x *CharacterAttrs) GetMpCurrent() int32 {
	if x != nil {
		return x.MpCurrent
	}
	return 0
}

func (x *CharacterAttrs) GetSoulMax() int32 {
	if x != nil {
		return x.SoulMax
	}
	return 0
}

func (x *CharacterAttrs) GetSoulCurrent() int32 {
	if x != nil {
		return x.SoulCurrent
	}
	return 0
}

type BaseAttrs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jing          int32                  `protobuf:"varint,1,opt,name=jing,proto3" json:"jing,omitempty"`
	Qi            int32                  `protobuf:"varint,2,opt,name=qi,proto3" json:"qi,omitempty"`
	Shen          int32                  `protobuf:"varint,3,opt,name=shen,proto3" json:"shen,omitempty"`
	QiYun         int32                  `protobuf:"varint,4,opt,name=qi_yun,json=qiYun,proto3" json:"qi_yun,omitempty"`
	WuXing        int32                  `protobuf:"varint,5,opt,name=wu_xing,json=wuXing,proto3" json:"wu_xing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseAttrs) Reset() {
	*x = BaseAttrs{}
	mi := &file_character_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseAttrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseAttrs) ProtoMessage() {}

func (x *BaseAttrs) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseAttrs.ProtoReflect.Descriptor instead.
func (*BaseAttrs) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{18}
}

func (x *BaseAttrs) GetJing() int32 {
	if x != nil {
		return x.Jing
	}
	return 0
}

func (x *BaseAttrs) GetQi() int32 {
	if x != nil {
		return x.Qi
	}
	return 0
}

func (x *BaseAttrs) GetShen() int32 {
	if x != nil {
		return x.Shen
	}
	return 0
}

func (x *BaseAttrs) GetQiYun() int32 {
	if x != nil {
		return x.QiYun
	}
	return 0
}

func (x *BaseAttrs) GetWuXing() int32 {
	if x != nil {
		return x.WuXing
	}
	return 0
}

type CurrentAttrs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HpMax         int32                  `protobuf:"varint,1,opt,name=hp_max,json=hpMax,proto3" json:"hp_max,omitempty"`
	HpCurrent     int32                  `protobuf:"varint,2,opt,name=hp_current,json=hpCurrent,proto3" json:"hp_current,omitempty"`
	MpMax         int32                  `protobuf:"varint,3,opt,name=mp_max,json=mpMax,proto3" json:"mp_max,omitempty"`
	MpCurrent     int32                  `protobuf:"varint,4,opt,name=mp_current,json=mpCurrent,proto3" json:"mp_current,omitempty"`
	SoulMax       int32                  `protobuf:"varint,5,opt,name=soul_max,json=soulMax,proto3" json:"soul_max,omitempty"`
	SoulCurrent   int32                  `protobuf:"varint,6,opt,name=soul_current,json=soulCurrent,proto3" json:"soul_current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentAttrs) Reset() {
	*x = CurrentAttrs{}
	mi := &file_character_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentAttrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentAttrs) ProtoMessage() {}

func (x *CurrentAttrs) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentAttrs.ProtoReflect.Descriptor instead.
func (*CurrentAttrs) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{19}
}

func (x *CurrentAttrs) GetHpMax() int32 {
	if x != nil {
		return x.HpMax
	}
	return 0
}

func (x *CurrentAttrs) GetHpCurrent() int32 {
	if x != nil {
		return x.HpCurrent
	}
	return 0
}

func (x *CurrentAttrs) GetMpMax() int32 {
	if x != nil {
		return x.MpMax
	}
	return 0
}

func (x *CurrentAttrs) GetMpCurrent() int32 {
	if x != nil {
		return x.MpCurrent
	}
	return 0
}

func (x *CurrentAttrs) GetSoulMax() int32 {
	if x != nil {
		return x.SoulMax
	}
	return 0
}

func (x *CurrentAttrs) GetSoulCurrent() int32 {
	if x != nil {
		return x.SoulCurrent
	}
	return 0
}

type DerivedAttrs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HpMax         int32                  `protobuf:"varint,1,opt,name=hp_max,json=hpMax,proto3" json:"hp_max,omitempty"`                // 气血上限 = 精×100
	MpMax         int32                  `protobuf:"varint,2,opt,name=mp_max,json=mpMax,proto3" json:"mp_max,omitempty"`                // 灵力上限 = 气×50
	SoulMax       int32                  `protobuf:"varint,3,opt,name=soul_max,json=soulMax,proto3" json:"soul_max,omitempty"`          // 魂力上限 = 神×30
	Physique      int32                  `protobuf:"varint,4,opt,name=physique,proto3" json:"physique,omitempty"`                       // 体魄 = 精×10
	Agility       int32                  `protobuf:"varint,5,opt,name=agility,proto3" json:"agility,omitempty"`                         // 身法 = 精×5
	BoneBase      int32                  `protobuf:"varint,6,opt,name=bone_base,json=boneBase,proto3" json:"bone_base,omitempty"`       // 根骨 = 精×8
	SkillPower    int32                  `protobuf:"varint,7,opt,name=skill_power,json=skillPower,proto3" json:"skill_power,omitempty"` // 功法威力 = 气×12
	SenseRange    int32                  `protobuf:"varint,8,opt,name=sense_range,json=senseRange,proto3" json:"sense_range,omitempty"` // 神识范围 = 神×15
	MentalWall    int32                  `protobuf:"varint,9,opt,name=mental_wall,json=mentalWall,proto3" json:"mental_wall,omitempty"` // 精神壁垒 = 神×8
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DerivedAttrs) Reset() {
	*x = DerivedAttrs{}
	mi := &file_character_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DerivedAttrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DerivedAttrs) ProtoMessage() {}

func (x *DerivedAttrs) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DerivedAttrs.ProtoReflect.Descriptor instead.
func (*DerivedAttrs) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{20}
}

func (x *DerivedAttrs) GetHpMax() int32 {
	if x != nil {
		return x.HpMax
	}
	return 0
}

func (x *DerivedAttrs) GetMpMax() int32 {
	if x != nil {
		return x.MpMax
	}
	return 0
}

func (x *DerivedAttrs) GetSoulMax() int32 {
	if x != nil {
		return x.SoulMax
	}
	return 0
}

func (x *DerivedAttrs) GetPhysique() int32 {
	if x != nil {
		return x.Physique
	}
	return 0
}

func (x *DerivedAttrs) GetAgility() int32 {
	if x != nil {
		return x.Agility
	}
	return 0
}

func (x *DerivedAttrs) GetBoneBase() int32 {
	if x != nil {
		return x.BoneBase
	}
	return 0
}

func (x *DerivedAttrs) GetSkillPower() int32 {
	if x != nil {
		return x.SkillPower
	}
	return 0
}

func (x *DerivedAttrs) GetSenseRange() int32 {
	if x != nil {
		return x.SenseRange
	}
	return 0
}

func (x *DerivedAttrs) GetMentalWall() int32 {
	if x != nil {
		return x.MentalWall
	}
	return 0
}

type RealmInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MajorStage       int32                  `protobuf:"varint,1,opt,name=major_stage,json=majorStage,proto3" json:"major_stage,omitempty"`       // 大境界：1=人阶 2=真人 3=仙 4=金仙
	MinorStage       int32                  `protobuf:"varint,2,opt,name=minor_stage,json=minorStage,proto3" json:"minor_stage,omitempty"`       // 小阶：1-9
	StageSegment     int32                  `protobuf:"varint,3,opt,name=stage_segment,json=stageSegment,proto3" json:"stage_segment,omitempty"` // 段格：0-9
	ExpJing          int64                  `protobuf:"varint,4,opt,name=exp_jing,json=expJing,proto3" json:"exp_jing,omitempty"`
	ExpQi            int64                  `protobuf:"varint,5,opt,name=exp_qi,json=expQi,proto3" json:"exp_qi,omitempty"`
	ExpShen          int64                  `protobuf:"varint,6,opt,name=exp_shen,json=expShen,proto3" json:"exp_shen,omitempty"`
	XinmoValue       int32                  `protobuf:"varint,7,opt,name=xinmo_value,json=xinmoValue,proto3" json:"xinmo_value,omitempty"` // 心魔值
	DaoXing          int32                  `protobuf:"varint,8,opt,name=dao_xing,json=daoXing,proto3" json:"dao_xing,omitempty"`          // 道行
	KarmaValue       int32                  `protobuf:"varint,9,opt,name=karma_value,json=karmaValue,proto3" json:"karma_value,omitempty"` // 因果值
	TribulationCount int32                  `protobuf:"varint,10,opt,name=tribulation_count,json=tribulationCount,proto3" json:"tribulation_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RealmInfo) Reset() {
	*x = RealmInfo{}
	mi := &file_character_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealmInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealmInfo) ProtoMessage() {}

func (x *RealmInfo) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealmInfo.ProtoReflect.Descriptor instead.
func (*RealmInfo) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{21}
}

func (x *RealmInfo) GetMajorStage() int32 {
	if x != nil {
		return x.MajorStage
	}
	return 0
}

func (x *RealmInfo) GetMinorStage() int32 {
	if x != nil {
		return x.MinorStage
	}
	return 0
}

func (x *RealmInfo) GetStageSegment() int32 {
	if x != nil {
		return x.StageSegment
	}
	return 0
}

func (x *RealmInfo) GetExpJing() int64 {
	if x != nil {
		return x.ExpJing
	}
	return 0
}

func (x *RealmInfo) GetExpQi() int64 {
	if x != nil {
		return x.ExpQi
	}
	return 0
}

func (x *RealmInfo) GetExpShen() int64 {
	if x != nil {
		return x.ExpShen
	}
	return 0
}

func (x *RealmInfo) GetXinmoValue() int32 {
	if x != nil {
		return x.XinmoValue
	}
	return 0
}

func (x *RealmInfo) GetDaoXing() int32 {
	if x != nil {
		return x.DaoXing
	}
	return 0
}

func (x *RealmInfo) GetKarmaValue() int32 {
	if x != nil {
		return x.KarmaValue
	}
	return 0
}

func (x *RealmInfo) GetTribulationCount() int32 {
	if x != nil {
		return x.TribulationCount
	}
	return 0
}

type QiElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElementType   int32                  `protobuf:"varint,1,opt,name=element_type,json=elementType,proto3" json:"element_type,omitempty"` // 1=金 2=木 3=水 4=火 5=土
	ElementName   string                 `protobuf:"bytes,2,opt,name=element_name,json=elementName,proto3" json:"element_name,omitempty"`  // 金/木/水/火/土
	Proficiency   int32                  `protobuf:"varint,3,opt,name=proficiency,proto3" json:"proficiency,omitempty"`
	IsCultivating bool                   `protobuf:"varint,4,opt,name=is_cultivating,json=isCultivating,proto3" json:"is_cultivating,omitempty"`
	StartedAt     string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QiElement) Reset() {
	*x = QiElement{}
	mi := &file_character_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QiElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QiElement) ProtoMessage() {}

func (x *QiElement) ProtoReflect() protoreflect.Message {
	mi := &file_character_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QiElement.ProtoReflect.Descriptor instead.
func (*QiElement) Descriptor() ([]byte, []int) {
	return file_character_proto_rawDescGZIP(), []int{22}
}

func (x *QiElement) GetElementType() int32 {
	if x != nil {
		return x.ElementType
	}
	return 0
}

func (x *QiElement) GetElementName() string {
	if x != nil {
		return x.ElementName
	}
	return ""
}

func (x *QiElement) GetProficiency() int32 {
	if x != nil {
		return x.Proficiency
	}
	return 0
}

func (x *QiElement) GetIsCultivating() bool {
	if x != nil {
		return x.IsCultivating
	}
	return false
}

func (x *QiElement) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

var File_character_proto protoreflect.FileDescriptor

const file_character_proto_rawDesc = "" +
	"\n" +
	"\x0fcharacter.proto\x12\x11xunxian.character\"?\n" +
	"\x11CreateCharRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x02 \x01(\x05R\x06gender\"\x8a\x02\n" +
	"\x12CreateCharResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12!\n" +
	"\fcharacter_id\x18\x03 \x01(\x03R\vcharacterId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x12\x12\n" +
	"\x04race\x18\x06 \x01(\x05R\x04race\x127\n" +
	"\x05attrs\x18\a \x01(\v2!.xunxian.character.CharacterAttrsR\x05attrs\x122\n" +
	"\x05realm\x18\b \x01(\v2\x1c.xunxian.character.RealmInfoR\x05realm\"7\n" +
	"\x12GetCharInfoRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\"\xd1\x03\n" +
	"\x13GetCharInfoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x124\n" +
	"\x04base\x18\x03 \x01(\v2 .xunxian.character.CharacterBaseR\x04base\x127\n" +
	"\x05attrs\x18\x04 \x01(\v2!.xunxian.character.CharacterAttrsR\x05attrs\x129\n" +
	"\aderived\x18\x05 \x01(\v2\x1f.xunxian.character.DerivedAttrsR\aderived\x122\n" +
	"\x05realm\x18\x06 \x01(\v2\x1c.xunxian.character.RealmInfoR\x05realm\x12=\n" +
	"\vqi_elements\x18\a \x03(\v2\x1c.xunxian.character.QiElementR\n" +
	"qiElements\x12#\n" +
	"\relement_count\x18\b \x01(\x05R\felementCount\x12%\n" +
	"\x0eexp_multiplier\x18\t \x01(\x01R\rexpMultiplier\x12+\n" +
	"\x11damage_multiplier\x18\n" +
	" \x01(\x01R\x10damageMultiplier\"8\n" +
	"\x13GetCharAttrsRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\"\xef\x01\n" +
	"\x14GetCharAttrsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12;\n" +
	"\n" +
	"base_attrs\x18\x03 \x01(\v2\x1c.xunxian.character.BaseAttrsR\tbaseAttrs\x129\n" +
	"\acurrent\x18\x04 \x01(\v2\x1f.xunxian.character.CurrentAttrsR\acurrent\x129\n" +
	"\aderived\x18\x05 \x01(\v2\x1f.xunxian.character.DerivedAttrsR\aderived\"\x7f\n" +
	"\rAddExpRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\x12\x19\n" +
	"\bexp_jing\x18\x02 \x01(\x03R\aexpJing\x12\x15\n" +
	"\x06exp_qi\x18\x03 \x01(\x03R\x05expQi\x12\x19\n" +
	"\bexp_shen\x18\x04 \x01(\x03R\aexpShen\"\xdd\x01\n" +
	"\x0eAddExpResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x19\n" +
	"\bexp_jing\x18\x03 \x01(\x03R\aexpJing\x12\x15\n" +
	"\x06exp_qi\x18\x04 \x01(\x03R\x05expQi\x12\x19\n" +
	"\bexp_shen\x18\x05 \x01(\x03R\aexpShen\x12\x17\n" +
	"\aexp_req\x18\x06 \x01(\x03R\x06expReq\x12\x1f\n" +
	"\vcan_upgrade\x18\a \x01(\bR\n" +
	"canUpgrade\x12\x1e\n" +
	"\n" +
	"multiplier\x18\b \x01(\x01R\n" +
	"multiplier\"8\n" +
	"\x13RealmUpgradeRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\"~\n" +
	"\x14RealmUpgradeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1f\n" +
	"\vmajor_stage\x18\x03 \x01(\x05R\n" +
	"majorStage\x12\x1f\n" +
	"\vminor_stage\x18\x04 \x01(\x05R\n" +
	"minorStage\"8\n" +
	"\x13BreakthroughRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\"\xb5\x01\n" +
	"\x14BreakthroughResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x1f\n" +
	"\vmajor_stage\x18\x04 \x01(\x05R\n" +
	"majorStage\x12\x1f\n" +
	"\vminor_stage\x18\x05 \x01(\x05R\n" +
	"minorStage\x12\x1d\n" +
	"\n" +
	"stage_name\x18\x06 \x01(\tR\tstageName\"Z\n" +
	"\x12QiCultivateRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\x12!\n" +
	"\felement_type\x18\x02 \x01(\x05R\velementType\"\xcd\x01\n" +
	"\x13QiCultivateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12!\n" +
	"\felement_type\x18\x03 \x01(\x05R\velementType\x12!\n" +
	"\felement_name\x18\x04 \x01(\tR\velementName\x12#\n" +
	"\relement_count\x18\x05 \x01(\x05R\felementCount\x12%\n" +
	"\x0eexp_multiplier\x18\x06 \x01(\x01R\rexpMultiplier\"9\n" +
	"\x14GetQiElementsRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\"\xf0\x01\n" +
	"\x15GetQiElementsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x128\n" +
	"\belements\x18\x03 \x03(\v2\x1c.xunxian.character.QiElementR\belements\x12#\n" +
	"\relement_count\x18\x04 \x01(\x05R\felementCount\x12%\n" +
	"\x0eexp_multiplier\x18\x05 \x01(\x01R\rexpMultiplier\x12+\n" +
	"\x11damage_multiplier\x18\x06 \x01(\x01R\x10damageMultiplier\"\xb0\x01\n" +
	"\rCharacterBase\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\x03R\vcharacterId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\x05R\x06gender\x12\x12\n" +
	"\x04race\x18\x05 \x01(\x05R\x04race\x12\x1d\n" +
	"\n" +
	"form_state\x18\x06 \x01(\x05R\tformState\"\xa2\x02\n" +
	"\x0eCharacterAttrs\x12\x12\n" +
	"\x04jing\x18\x01 \x01(\x05R\x04jing\x12\x0e\n" +
	"\x02qi\x18\x02 \x01(\x05R\x02qi\x12\x12\n" +
	"\x04shen\x18\x03 \x01(\x05R\x04shen\x12\x15\n" +
	"\x06qi_yun\x18\x04 \x01(\x05R\x05qiYun\x12\x17\n" +
	"\awu_xing\x18\x05 \x01(\x05R\x06wuXing\x12\x15\n" +
	"\x06hp_max\x18\x06 \x01(\x05R\x05hpMax\x12\x1d\n" +
	"\n" +
	"hp_current\x18\a \x01(\x05R\thpCurrent\x12\x15\n" +
	"\x06mp_max\x18\b \x01(\x05R\x05mpMax\x12\x1d\n" +
	"\n" +
	"mp_current\x18\t \x01(\x05R\tmpCurrent\x12\x19\n" +
	"\bsoul_max\x18\n" +
	" \x01(\x05R\asoulMax\x12!\n" +
	"\fsoul_current\x18\v \x01(\x05R\vsoulCurrent\"s\n" +
	"\tBaseAttrs\x12\x12\n" +
	"\x04jing\x18\x01 \x01(\x05R\x04jing\x12\x0e\n" +
	"\x02qi\x18\x02 \x01(\x05R\x02qi\x12\x12\n" +
	"\x04shen\x18\x03 \x01(\x05R\x04shen\x12\x15\n" +
	"\x06qi_yun\x18\x04 \x01(\x05R\x05qiYun\x12\x17\n" +
	"\awu_xing\x18\x05 \x01(\x05R\x06wuXing\"\xb8\x01\n" +
	"\fCurrentAttrs\x12\x15\n" +
	"\x06hp_max\x18\x01 \x01(\x05R\x05hpMax\x12\x1d\n" +
	"\n" +
	"hp_current\x18\x02 \x01(\x05R\thpCurrent\x12\x15\n" +
	"\x06mp_max\x18\x03 \x01(\x05R\x05mpMax\x12\x1d\n" +
	"\n" +
	"mp_current\x18\x04 \x01(\x05R\tmpCurrent\x12\x19\n" +
	"\bsoul_max\x18\x05 \x01(\x05R\asoulMax\x12!\n" +
	"\fsoul_current\x18\x06 \x01(\x05R\vsoulCurrent\"\x8d\x02\n" +
	"\fDerivedAttrs\x12\x15\n" +
	"\x06hp_max\x18\x01 \x01(\x05R\x05hpMax\x12\x15\n" +
	"\x06mp_max\x18\x02 \x01(\x05R\x05mpMax\x12\x19\n" +
	"\bsoul_max\x18\x03 \x01(\x05R\asoulMax\x12\x1a\n" +
	"\bphysique\x18\x04 \x01(\x05R\bphysique\x12\x18\n" +
	"\aagility\x18\x05 \x01(\x05R\aagility\x12\x1b\n" +
	"\tbone_base\x18\x06 \x01(\x05R\bboneBase\x12\x1f\n" +
	"\vskill_power\x18\a \x01(\x05R\n" +
	"skillPower\x12\x1f\n" +
	"\vsense_range\x18\b \x01(\x05R\n" +
	"senseRange\x12\x1f\n" +
	"\vmental_wall\x18\t \x01(\x05R\n" +
	"mentalWall\"\xc9\x02\n" +
	"\tRealmInfo\x12\x1f\n" +
	"\vmajor_stage\x18\x01 \x01(\x05R\n" +
	"majorStage\x12\x1f\n" +
	"\vminor_stage\x18\x02 \x01(\x05R\n" +
	"minorStage\x12#\n" +
	"\rstage_segment\x18\x03 \x01(\x05R\fstageSegment\x12\x19\n" +
	"\bexp_jing\x18\x04 \x01(\x03R\aexpJing\x12\x15\n" +
	"\x06exp_qi\x18\x05 \x01(\x03R\x05expQi\x12\x19\n" +
	"\bexp_shen\x18\x06 \x01(\x03R\aexpShen\x12\x1f\n" +
	"\vxinmo_value\x18\a \x01(\x05R\n" +
	"xinmoValue\x12\x19\n" +
	"\bdao_xing\x18\b \x01(\x05R\adaoXing\x12\x1f\n" +
	"\vkarma_value\x18\t \x01(\x05R\n" +
	"karmaValue\x12+\n" +
	"\x11tribulation_count\x18\n" +
	" \x01(\x05R\x10tribulationCount\"\xb9\x01\n" +
	"\tQiElement\x12!\n" +
	"\felement_type\x18\x01 \x01(\x05R\velementType\x12!\n" +
	"\felement_name\x18\x02 \x01(\tR\velementName\x12 \n" +
	"\vproficiency\x18\x03 \x01(\x05R\vproficiency\x12%\n" +
	"\x0eis_cultivating\x18\x04 \x01(\bR\risCultivating\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAtB\x19Z\x17xunxian/proto/characterb\x06proto3"

var (
	file_character_proto_rawDescOnce sync.Once
	file_character_proto_rawDescData []byte
)

func file_character_proto_rawDescGZIP() []byte {
	file_character_proto_rawDescOnce.Do(func() {
		file_character_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_character_proto_rawDesc), len(file_character_proto_rawDesc)))
	})
	return file_character_proto_rawDescData
}

var file_character_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_character_proto_goTypes = []any{
	(*CreateCharRequest)(nil),     // 0: xunxian.character.CreateCharRequest
	(*CreateCharResponse)(nil),    // 1: xunxian.character.CreateCharResponse
	(*GetCharInfoRequest)(nil),    // 2: xunxian.character.GetCharInfoRequest
	(*GetCharInfoResponse)(nil),   // 3: xunxian.character.GetCharInfoResponse
	(*GetCharAttrsRequest)(nil),   // 4: xunxian.character.GetCharAttrsRequest
	(*GetCharAttrsResponse)(nil),  // 5: xunxian.character.GetCharAttrsResponse
	(*AddExpRequest)(nil),         // 6: xunxian.character.AddExpRequest
	(*AddExpResponse)(nil),        // 7: xunxian.character.AddExpResponse
	(*RealmUpgradeRequest)(nil),   // 8: xunxian.character.RealmUpgradeRequest
	(*RealmUpgradeResponse)(nil),  // 9: xunxian.character.RealmUpgradeResponse
	(*BreakthroughRequest)(nil),   // 10: xunxian.character.BreakthroughRequest
	(*BreakthroughResponse)(nil),  // 11: xunxian.character.BreakthroughResponse
	(*QiCultivateRequest)(nil),    // 12: xunxian.character.QiCultivateRequest
	(*QiCultivateResponse)(nil),   // 13: xunxian.character.QiCultivateResponse
	(*GetQiElementsRequest)(nil),  // 14: xunxian.character.GetQiElementsRequest
	(*GetQiElementsResponse)(nil), // 15: xunxian.character.GetQiElementsResponse
	(*CharacterBase)(nil),         // 16: xunxian.character.CharacterBase
	(*CharacterAttrs)(nil),        // 17: xunxian.character.CharacterAttrs
	(*BaseAttrs)(nil),             // 18: xunxian.character.BaseAttrs
	(*CurrentAttrs)(nil),          // 19: xunxian.character.CurrentAttrs
	(*DerivedAttrs)(nil),          // 20: xunxian.character.DerivedAttrs
	(*RealmInfo)(nil),             // 21: xunxian.character.RealmInfo
	(*QiElement)(nil),             // 22: xunxian.character.QiElement
}
var file_character_proto_depIdxs = []int32{
	17, // 0: xunxian.character.CreateCharResponse.attrs:type_name -> xunxian.character.CharacterAttrs
	21, // 1: xunxian.character.CreateCharResponse.realm:type_name -> xunxian.character.RealmInfo
	16, // 2: xunxian.character.GetCharInfoResponse.base:type_name -> xunxian.character.CharacterBase
	17, // 3: xunxian.character.GetCharInfoResponse.attrs:type_name -> xunxian.character.CharacterAttrs
	20, // 4: xunxian.character.GetCharInfoResponse.derived:type_name -> xunxian.character.DerivedAttrs
	21, // 5: xunxian.character.GetCharInfoResponse.realm:type_name -> xunxian.character.RealmInfo
	22, // 6: xunxian.character.GetCharInfoResponse.qi_elements:type_name -> xunxian.character.QiElement
	18, // 7: xunxian.character.GetCharAttrsResponse.base_attrs:type_name -> xunxian.character.BaseAttrs
	19, // 8: xunxian.character.GetCharAttrsResponse.current:type_name -> xunxian.character.CurrentAttrs
	20, // 9: xunxian.character.GetCharAttrsResponse.derived:type_name -> xunxian.character.DerivedAttrs
	22, // 10: xunxian.character.GetQiElementsResponse.elements:type_name -> xunxian.character.QiElement
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_character_proto_init() }
func file_character_proto_init() {
	if File_character_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_character_proto_rawDesc), len(file_character_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_character_proto_goTypes,
		DependencyIndexes: file_character_proto_depIdxs,
		MessageInfos:      file_character_proto_msgTypes,
	}.Build()
	File_character_proto = out.File
	file_character_proto_goTypes = nil
	file_character_proto_depIdxs = nil
}
