// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: player.proto

package player

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建角色
type CreateCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`      // 2-8汉字
	Gender        int32                  `protobuf:"varint,2,opt,name=gender,proto3" json:"gender,omitempty"` // 1男 2女
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterRequest) Reset() {
	*x = CreateCharacterRequest{}
	mi := &file_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterRequest) ProtoMessage() {}

func (x *CreateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterRequest.ProtoReflect.Descriptor instead.
func (*CreateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCharacterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCharacterRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

type CreateCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	PlayerId      int64                  `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Gender        int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Attrs         *PlayerAttrs           `protobuf:"bytes,6,opt,name=attrs,proto3" json:"attrs,omitempty"`
	SceneId       int32                  `protobuf:"varint,7,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	PosX          float32                `protobuf:"fixed32,8,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          float32                `protobuf:"fixed32,9,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterResponse) Reset() {
	*x = CreateCharacterResponse{}
	mi := &file_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterResponse) ProtoMessage() {}

func (x *CreateCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterResponse.ProtoReflect.Descriptor instead.
func (*CreateCharacterResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCharacterResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateCharacterResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateCharacterResponse) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *CreateCharacterResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCharacterResponse) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *CreateCharacterResponse) GetAttrs() *PlayerAttrs {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *CreateCharacterResponse) GetSceneId() int32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *CreateCharacterResponse) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *CreateCharacterResponse) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

// 查询角色信息
type GetPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRequest) Reset() {
	*x = GetPlayerRequest{}
	mi := &file_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRequest) ProtoMessage() {}

func (x *GetPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlayerRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type GetPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Info          *PlayerInfo            `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerResponse) Reset() {
	*x = GetPlayerResponse{}
	mi := &file_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerResponse) ProtoMessage() {}

func (x *GetPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlayerResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPlayerResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetPlayerResponse) GetInfo() *PlayerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// 查询角色属性
type GetPlayerAttrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerAttrRequest) Reset() {
	*x = GetPlayerAttrRequest{}
	mi := &file_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerAttrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerAttrRequest) ProtoMessage() {}

func (x *GetPlayerAttrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerAttrRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerAttrRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{4}
}

func (x *GetPlayerAttrRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type GetPlayerAttrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Attrs         *PlayerAttrs           `protobuf:"bytes,3,opt,name=attrs,proto3" json:"attrs,omitempty"`
	HiddenAttrs   *HiddenAttrs           `protobuf:"bytes,4,opt,name=hidden_attrs,json=hiddenAttrs,proto3" json:"hidden_attrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerAttrResponse) Reset() {
	*x = GetPlayerAttrResponse{}
	mi := &file_player_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerAttrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerAttrResponse) ProtoMessage() {}

func (x *GetPlayerAttrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerAttrResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerAttrResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{5}
}

func (x *GetPlayerAttrResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPlayerAttrResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetPlayerAttrResponse) GetAttrs() *PlayerAttrs {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *GetPlayerAttrResponse) GetHiddenAttrs() *HiddenAttrs {
	if x != nil {
		return x.HiddenAttrs
	}
	return nil
}

// 随机名称
type RandomNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gender        int32                  `protobuf:"varint,1,opt,name=gender,proto3" json:"gender,omitempty"` // 可选，用于生成性别相关名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomNameRequest) Reset() {
	*x = RandomNameRequest{}
	mi := &file_player_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomNameRequest) ProtoMessage() {}

func (x *RandomNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomNameRequest.ProtoReflect.Descriptor instead.
func (*RandomNameRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{6}
}

func (x *RandomNameRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

type RandomNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomNameResponse) Reset() {
	*x = RandomNameResponse{}
	mi := &file_player_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomNameResponse) ProtoMessage() {}

func (x *RandomNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomNameResponse.ProtoReflect.Descriptor instead.
func (*RandomNameResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{7}
}

func (x *RandomNameResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RandomNameResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RandomNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 名称校验
type ValidateNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateNameRequest) Reset() {
	*x = ValidateNameRequest{}
	mi := &file_player_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateNameRequest) ProtoMessage() {}

func (x *ValidateNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateNameRequest.ProtoReflect.Descriptor instead.
func (*ValidateNameRequest) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ValidateNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Valid         bool                   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateNameResponse) Reset() {
	*x = ValidateNameResponse{}
	mi := &file_player_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateNameResponse) ProtoMessage() {}

func (x *ValidateNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateNameResponse.ProtoReflect.Descriptor instead.
func (*ValidateNameResponse) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateNameResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ValidateNameResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ValidateNameResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Gender        int32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Race          int32                  `protobuf:"varint,5,opt,name=race,proto3" json:"race,omitempty"`                               // 种族，初版只有人族
	LevelStage    int32                  `protobuf:"varint,6,opt,name=level_stage,json=levelStage,proto3" json:"level_stage,omitempty"` // 境界阶段：1人 2真人 3仙 4金仙
	LevelTier     int32                  `protobuf:"varint,7,opt,name=level_tier,json=levelTier,proto3" json:"level_tier,omitempty"`    // 境界等级：1-9
	LevelStep     int32                  `protobuf:"varint,8,opt,name=level_step,json=levelStep,proto3" json:"level_step,omitempty"`    // 境界段位：1-10
	SceneId       int32                  `protobuf:"varint,9,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`          // 当前场景ID
	PosX          float32                `protobuf:"fixed32,10,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          float32                `protobuf:"fixed32,11,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	Attrs         *PlayerAttrs           `protobuf:"bytes,12,opt,name=attrs,proto3" json:"attrs,omitempty"`
	HiddenAttrs   *HiddenAttrs           `protobuf:"bytes,13,opt,name=hidden_attrs,json=hiddenAttrs,proto3" json:"hidden_attrs,omitempty"`
	Status        string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"` // normal / public_enemy / thunder / ghost / beast
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_player_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerInfo) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerInfo) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *PlayerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *PlayerInfo) GetRace() int32 {
	if x != nil {
		return x.Race
	}
	return 0
}

func (x *PlayerInfo) GetLevelStage() int32 {
	if x != nil {
		return x.LevelStage
	}
	return 0
}

func (x *PlayerInfo) GetLevelTier() int32 {
	if x != nil {
		return x.LevelTier
	}
	return 0
}

func (x *PlayerInfo) GetLevelStep() int32 {
	if x != nil {
		return x.LevelStep
	}
	return 0
}

func (x *PlayerInfo) GetSceneId() int32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *PlayerInfo) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *PlayerInfo) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *PlayerInfo) GetAttrs() *PlayerAttrs {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *PlayerInfo) GetHiddenAttrs() *HiddenAttrs {
	if x != nil {
		return x.HiddenAttrs
	}
	return nil
}

func (x *PlayerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PlayerAttrs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jing          int32                  `protobuf:"varint,1,opt,name=jing,proto3" json:"jing,omitempty"`                      // 精（肉身）
	QiMetal       int32                  `protobuf:"varint,2,opt,name=qi_metal,json=qiMetal,proto3" json:"qi_metal,omitempty"` // 金之气
	QiWood        int32                  `protobuf:"varint,3,opt,name=qi_wood,json=qiWood,proto3" json:"qi_wood,omitempty"`    // 木之气
	QiWater       int32                  `protobuf:"varint,4,opt,name=qi_water,json=qiWater,proto3" json:"qi_water,omitempty"` // 水之气
	QiFire        int32                  `protobuf:"varint,5,opt,name=qi_fire,json=qiFire,proto3" json:"qi_fire,omitempty"`    // 火之气
	QiEarth       int32                  `protobuf:"varint,6,opt,name=qi_earth,json=qiEarth,proto3" json:"qi_earth,omitempty"` // 土之气
	Shen          int32                  `protobuf:"varint,7,opt,name=shen,proto3" json:"shen,omitempty"`                      // 神（灵魂）
	Luck          float64                `protobuf:"fixed64,8,opt,name=luck,proto3" json:"luck,omitempty"`                     // 气运
	Savvy         float64                `protobuf:"fixed64,9,opt,name=savvy,proto3" json:"savvy,omitempty"`                   // 悟性
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerAttrs) Reset() {
	*x = PlayerAttrs{}
	mi := &file_player_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAttrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAttrs) ProtoMessage() {}

func (x *PlayerAttrs) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAttrs.ProtoReflect.Descriptor instead.
func (*PlayerAttrs) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerAttrs) GetJing() int32 {
	if x != nil {
		return x.Jing
	}
	return 0
}

func (x *PlayerAttrs) GetQiMetal() int32 {
	if x != nil {
		return x.QiMetal
	}
	return 0
}

func (x *PlayerAttrs) GetQiWood() int32 {
	if x != nil {
		return x.QiWood
	}
	return 0
}

func (x *PlayerAttrs) GetQiWater() int32 {
	if x != nil {
		return x.QiWater
	}
	return 0
}

func (x *PlayerAttrs) GetQiFire() int32 {
	if x != nil {
		return x.QiFire
	}
	return 0
}

func (x *PlayerAttrs) GetQiEarth() int32 {
	if x != nil {
		return x.QiEarth
	}
	return 0
}

func (x *PlayerAttrs) GetShen() int32 {
	if x != nil {
		return x.Shen
	}
	return 0
}

func (x *PlayerAttrs) GetLuck() float64 {
	if x != nil {
		return x.Luck
	}
	return 0
}

func (x *PlayerAttrs) GetSavvy() float64 {
	if x != nil {
		return x.Savvy
	}
	return 0
}

type HiddenAttrs struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Causality        int32                  `protobuf:"varint,1,opt,name=causality,proto3" json:"causality,omitempty"`                                       // 因果（隐藏）
	InnerDemon       int32                  `protobuf:"varint,2,opt,name=inner_demon,json=innerDemon,proto3" json:"inner_demon,omitempty"`                   // 心魔（隐藏）
	DaoAge           int32                  `protobuf:"varint,3,opt,name=dao_age,json=daoAge,proto3" json:"dao_age,omitempty"`                               // 道行（隐藏）
	TribulationCount int32                  `protobuf:"varint,4,opt,name=tribulation_count,json=tribulationCount,proto3" json:"tribulation_count,omitempty"` // 天劫次数（隐藏）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HiddenAttrs) Reset() {
	*x = HiddenAttrs{}
	mi := &file_player_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HiddenAttrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiddenAttrs) ProtoMessage() {}

func (x *HiddenAttrs) ProtoReflect() protoreflect.Message {
	mi := &file_player_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiddenAttrs.ProtoReflect.Descriptor instead.
func (*HiddenAttrs) Descriptor() ([]byte, []int) {
	return file_player_proto_rawDescGZIP(), []int{12}
}

func (x *HiddenAttrs) GetCausality() int32 {
	if x != nil {
		return x.Causality
	}
	return 0
}

func (x *HiddenAttrs) GetInnerDemon() int32 {
	if x != nil {
		return x.InnerDemon
	}
	return 0
}

func (x *HiddenAttrs) GetDaoAge() int32 {
	if x != nil {
		return x.DaoAge
	}
	return 0
}

func (x *HiddenAttrs) GetTribulationCount() int32 {
	if x != nil {
		return x.TribulationCount
	}
	return 0
}

var File_player_proto protoreflect.FileDescriptor

const file_player_proto_rawDesc = "" +
	"\n" +
	"\fplayer.proto\x12\x0exunxian.player\"D\n" +
	"\x16CreateCharacterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x02 \x01(\x05R\x06gender\"\x80\x02\n" +
	"\x17CreateCharacterResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\x03R\bplayerId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x121\n" +
	"\x05attrs\x18\x06 \x01(\v2\x1b.xunxian.player.PlayerAttrsR\x05attrs\x12\x19\n" +
	"\bscene_id\x18\a \x01(\x05R\asceneId\x12\x13\n" +
	"\x05pos_x\x18\b \x01(\x02R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\t \x01(\x02R\x04posY\"/\n" +
	"\x10GetPlayerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"i\n" +
	"\x11GetPlayerResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12.\n" +
	"\x04info\x18\x03 \x01(\v2\x1a.xunxian.player.PlayerInfoR\x04info\"3\n" +
	"\x14GetPlayerAttrRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"\xb0\x01\n" +
	"\x15GetPlayerAttrResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x121\n" +
	"\x05attrs\x18\x03 \x01(\v2\x1b.xunxian.player.PlayerAttrsR\x05attrs\x12>\n" +
	"\fhidden_attrs\x18\x04 \x01(\v2\x1b.xunxian.player.HiddenAttrsR\vhiddenAttrs\"+\n" +
	"\x11RandomNameRequest\x12\x16\n" +
	"\x06gender\x18\x01 \x01(\x05R\x06gender\"N\n" +
	"\x12RandomNameResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\")\n" +
	"\x13ValidateNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"R\n" +
	"\x14ValidateNameResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\"\xb7\x03\n" +
	"\n" +
	"PlayerInfo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\x05R\x06gender\x12\x12\n" +
	"\x04race\x18\x05 \x01(\x05R\x04race\x12\x1f\n" +
	"\vlevel_stage\x18\x06 \x01(\x05R\n" +
	"levelStage\x12\x1d\n" +
	"\n" +
	"level_tier\x18\a \x01(\x05R\tlevelTier\x12\x1d\n" +
	"\n" +
	"level_step\x18\b \x01(\x05R\tlevelStep\x12\x19\n" +
	"\bscene_id\x18\t \x01(\x05R\asceneId\x12\x13\n" +
	"\x05pos_x\x18\n" +
	" \x01(\x02R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\v \x01(\x02R\x04posY\x121\n" +
	"\x05attrs\x18\f \x01(\v2\x1b.xunxian.player.PlayerAttrsR\x05attrs\x12>\n" +
	"\fhidden_attrs\x18\r \x01(\v2\x1b.xunxian.player.HiddenAttrsR\vhiddenAttrs\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\"\xe2\x01\n" +
	"\vPlayerAttrs\x12\x12\n" +
	"\x04jing\x18\x01 \x01(\x05R\x04jing\x12\x19\n" +
	"\bqi_metal\x18\x02 \x01(\x05R\aqiMetal\x12\x17\n" +
	"\aqi_wood\x18\x03 \x01(\x05R\x06qiWood\x12\x19\n" +
	"\bqi_water\x18\x04 \x01(\x05R\aqiWater\x12\x17\n" +
	"\aqi_fire\x18\x05 \x01(\x05R\x06qiFire\x12\x19\n" +
	"\bqi_earth\x18\x06 \x01(\x05R\aqiEarth\x12\x12\n" +
	"\x04shen\x18\a \x01(\x05R\x04shen\x12\x12\n" +
	"\x04luck\x18\b \x01(\x01R\x04luck\x12\x14\n" +
	"\x05savvy\x18\t \x01(\x01R\x05savvy\"\x92\x01\n" +
	"\vHiddenAttrs\x12\x1c\n" +
	"\tcausality\x18\x01 \x01(\x05R\tcausality\x12\x1f\n" +
	"\vinner_demon\x18\x02 \x01(\x05R\n" +
	"innerDemon\x12\x17\n" +
	"\adao_age\x18\x03 \x01(\x05R\x06daoAge\x12+\n" +
	"\x11tribulation_count\x18\x04 \x01(\x05R\x10tribulationCountB\x16Z\x14xunxian/proto/playerb\x06proto3"

var (
	file_player_proto_rawDescOnce sync.Once
	file_player_proto_rawDescData []byte
)

func file_player_proto_rawDescGZIP() []byte {
	file_player_proto_rawDescOnce.Do(func() {
		file_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)))
	})
	return file_player_proto_rawDescData
}

var file_player_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_player_proto_goTypes = []any{
	(*CreateCharacterRequest)(nil),  // 0: xunxian.player.CreateCharacterRequest
	(*CreateCharacterResponse)(nil), // 1: xunxian.player.CreateCharacterResponse
	(*GetPlayerRequest)(nil),        // 2: xunxian.player.GetPlayerRequest
	(*GetPlayerResponse)(nil),       // 3: xunxian.player.GetPlayerResponse
	(*GetPlayerAttrRequest)(nil),    // 4: xunxian.player.GetPlayerAttrRequest
	(*GetPlayerAttrResponse)(nil),   // 5: xunxian.player.GetPlayerAttrResponse
	(*RandomNameRequest)(nil),       // 6: xunxian.player.RandomNameRequest
	(*RandomNameResponse)(nil),      // 7: xunxian.player.RandomNameResponse
	(*ValidateNameRequest)(nil),     // 8: xunxian.player.ValidateNameRequest
	(*ValidateNameResponse)(nil),    // 9: xunxian.player.ValidateNameResponse
	(*PlayerInfo)(nil),              // 10: xunxian.player.PlayerInfo
	(*PlayerAttrs)(nil),             // 11: xunxian.player.PlayerAttrs
	(*HiddenAttrs)(nil),             // 12: xunxian.player.HiddenAttrs
}
var file_player_proto_depIdxs = []int32{
	11, // 0: xunxian.player.CreateCharacterResponse.attrs:type_name -> xunxian.player.PlayerAttrs
	10, // 1: xunxian.player.GetPlayerResponse.info:type_name -> xunxian.player.PlayerInfo
	11, // 2: xunxian.player.GetPlayerAttrResponse.attrs:type_name -> xunxian.player.PlayerAttrs
	12, // 3: xunxian.player.GetPlayerAttrResponse.hidden_attrs:type_name -> xunxian.player.HiddenAttrs
	11, // 4: xunxian.player.PlayerInfo.attrs:type_name -> xunxian.player.PlayerAttrs
	12, // 5: xunxian.player.PlayerInfo.hidden_attrs:type_name -> xunxian.player.HiddenAttrs
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_player_proto_init() }
func file_player_proto_init() {
	if File_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_player_proto_rawDesc), len(file_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_player_proto_goTypes,
		DependencyIndexes: file_player_proto_depIdxs,
		MessageInfos:      file_player_proto_msgTypes,
	}.Build()
	File_player_proto = out.File
	file_player_proto_goTypes = nil
	file_player_proto_depIdxs = nil
}
